#include "office_state.h"
#include <Arduino.h>
#include <string.h>

// ── Reading tools (show reading animation instead of typing) ──
static bool isReadingTool(const char* tool) {
    if (!tool || tool[0] == '\0') return false;
    return (strcmp(tool, "Read") == 0 || strcmp(tool, "Grep") == 0 ||
            strcmp(tool, "Glob") == 0 || strcmp(tool, "WebFetch") == 0 ||
            strcmp(tool, "WebSearch") == 0);
}

void OfficeState::init() {
    memset(_chars, 0, sizeof(_chars));
    for (int i = 0; i < MAX_AGENTS; i++) {
        _chars[i].alive = false;
        _chars[i].seatIdx = -1;
        _chars[i].agentId = -1;
    }
    initTileMap();
    _connected = false;
    _lastHeartbeatMs = 0;
}

void OfficeState::spawnAllCharacters() {
    for (int i = 0; i < MAX_AGENTS; i++) {
        Character& ch = _chars[i];
        memset(&ch, 0, sizeof(Character));
        ch.alive = true;
        ch.id = (uint8_t)i;
        ch.palette = (uint8_t)(i % NUM_PALETTES);
        ch.state = CharState::IDLE;
        ch.isActive = false;
        ch.seatIdx = -1;
        ch.agentId = -1;
        ch.homeZone = (i < 3) ? SocialZone::BREAK_ROOM : SocialZone::LIBRARY;
        ch.dir = Dir::DOWN;
        ch.frame = 0;
        ch.frameTimer = 0;
        ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
        ch.wanderCount = 0;
        ch.wanderLimit = (uint8_t)randomInt(WANDER_MOVES_MIN, WANDER_MOVES_MAX);
        ch.pathLen = 0;
        ch.pathIdx = 0;
        ch.bubbleType = 0;
        ch.bubbleTimer = 0;
        ch.effectTimer = 0;
        ch.toolName[0] = '\0';

        // Place at a random walkable tile within home zone
        int colMin, colMax, rowMin, rowMax;
        if (ch.homeZone == SocialZone::BREAK_ROOM) {
            colMin = ZONE_BREAK_COL_MIN; colMax = ZONE_BREAK_COL_MAX;
            rowMin = ZONE_BREAK_ROW_MIN; rowMax = ZONE_BREAK_ROW_MAX;
        } else {
            colMin = ZONE_LIB_COL_MIN; colMax = ZONE_LIB_COL_MAX;
            rowMin = ZONE_LIB_ROW_MIN; rowMax = ZONE_LIB_ROW_MAX;
        }

        bool placed = false;
        for (int attempt = 0; attempt < 40; attempt++) {
            int8_t col = (int8_t)randomInt(colMin, colMax);
            int8_t row = (int8_t)randomInt(rowMin, rowMax);
            if (isWalkable(col, row)) {
                ch.tileCol = col;
                ch.tileRow = row;
                ch.x = col * TILE_SIZE + TILE_SIZE / 2.0f;
                ch.y = row * TILE_SIZE + TILE_SIZE / 2.0f;
                placed = true;
                break;
            }
        }
        if (!placed) {
            // Fallback: scan zone for any walkable tile
            for (int r = rowMin; r <= rowMax && !placed; r++) {
                for (int c = colMin; c <= colMax && !placed; c++) {
                    if (isWalkable((int8_t)c, (int8_t)r)) {
                        ch.tileCol = (int8_t)c;
                        ch.tileRow = (int8_t)r;
                        ch.x = c * TILE_SIZE + TILE_SIZE / 2.0f;
                        ch.y = r * TILE_SIZE + TILE_SIZE / 2.0f;
                        placed = true;
                    }
                }
            }
        }
        if (!placed) {
            // Last resort: center of map
            ch.tileCol = 10;
            ch.tileRow = 3;
            ch.x = 10 * TILE_SIZE + TILE_SIZE / 2.0f;
            ch.y = 3 * TILE_SIZE + TILE_SIZE / 2.0f;
        }
    }
}

// Generated by tools/layout_editor.html
void OfficeState::initTileMap() {
    // Initialize all tiles
    for (int r = 0; r < GRID_ROWS; r++) {
        for (int c = 0; c < GRID_COLS; c++) {
            _tiles[r][c] = TileType::FLOOR;
        }
    }
    // Mark desk tiles as blocked (2x2 desks)
    for (int i = 0; i < NUM_WORKSTATIONS; i++) {
        const auto& ws = WORKSTATIONS[i];
        for (int dr = 0; dr < 2; dr++) {
            for (int dc = 0; dc < 2; dc++) {
                int r = ws.deskRow + dr;
                int c = ws.deskCol + dc;
                if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) {
                    _tiles[r][c] = TileType::BLOCKED;
                }
            }
        }
    }
    // Mark decorative furniture as blocked
    // Water Cooler at col 12, rows 0-2
    _tiles[0][12] = TileType::BLOCKED;
    _tiles[1][12] = TileType::BLOCKED;
    _tiles[2][12] = TileType::BLOCKED;
    // Counter Top at col 16, row 1
    _tiles[1][16] = TileType::BLOCKED;
    _tiles[1][17] = TileType::BLOCKED;
    // Counter Top at col 14, row 1
    _tiles[1][14] = TileType::BLOCKED;
    _tiles[1][15] = TileType::BLOCKED;
    // Counter Bottom A at col 14, row 2
    _tiles[2][14] = TileType::BLOCKED;
    _tiles[2][15] = TileType::BLOCKED;
    // Counter Bottom A at col 16, row 2
    _tiles[2][16] = TileType::BLOCKED;
    _tiles[2][17] = TileType::BLOCKED;
    // Coffee Maker at col 16, rows 0-1
    _tiles[0][16] = TileType::BLOCKED;
    _tiles[1][16] = TileType::BLOCKED;
    // Coffee Maker at col 17, rows 0-1
    _tiles[0][17] = TileType::BLOCKED;
    _tiles[1][17] = TileType::BLOCKED;
    // Vending Machine at col 18, rows 0-2
    _tiles[0][18] = TileType::BLOCKED;
    _tiles[0][19] = TileType::BLOCKED;
    _tiles[1][18] = TileType::BLOCKED;
    _tiles[1][19] = TileType::BLOCKED;
    _tiles[2][18] = TileType::BLOCKED;
    _tiles[2][19] = TileType::BLOCKED;
    // Plant Top E at col 13, row 1
    _tiles[1][13] = TileType::BLOCKED;
    // Plant Bottom White at col 13, row 2
    _tiles[2][13] = TileType::BLOCKED;
    // Computer E at col 1, row 12
    _tiles[12][1] = TileType::BLOCKED;
    _tiles[12][2] = TileType::BLOCKED;
    _tiles[12][3] = TileType::BLOCKED;
    // Computer G at col 7, row 12
    _tiles[12][7] = TileType::BLOCKED;
    // Laptop B at col 2, rows 7-8
    _tiles[7][2] = TileType::BLOCKED;
    _tiles[8][2] = TileType::BLOCKED;
    // Computer B at col 7, rows 7-8
    _tiles[7][7] = TileType::BLOCKED;
    _tiles[7][8] = TileType::BLOCKED;
    _tiles[8][7] = TileType::BLOCKED;
    _tiles[8][8] = TileType::BLOCKED;
    // Computer F at col 7, rows 4-5
    _tiles[4][7] = TileType::BLOCKED;
    _tiles[4][8] = TileType::BLOCKED;
    _tiles[5][7] = TileType::BLOCKED;
    _tiles[5][8] = TileType::BLOCKED;
    // Laptop E at col 2, row 5
    _tiles[5][2] = TileType::BLOCKED;
    // Plant Bottom Brown at col 10, row 13
    _tiles[13][10] = TileType::BLOCKED;
    // Plant Bottom Brown at col 0, row 13
    _tiles[13][0] = TileType::BLOCKED;
    // Plant Top C at col 0, row 12
    _tiles[12][0] = TileType::BLOCKED;
    // Plant Top D at col 10, row 12
    _tiles[12][10] = TileType::BLOCKED;
    // Bookshelf A at col 12, rows 5-7
    _tiles[5][12] = TileType::BLOCKED;
    _tiles[5][13] = TileType::BLOCKED;
    _tiles[6][12] = TileType::BLOCKED;
    _tiles[6][13] = TileType::BLOCKED;
    _tiles[7][12] = TileType::BLOCKED;
    _tiles[7][13] = TileType::BLOCKED;
    // Bookshelf A at col 16, rows 5-7
    _tiles[5][16] = TileType::BLOCKED;
    _tiles[5][17] = TileType::BLOCKED;
    _tiles[6][16] = TileType::BLOCKED;
    _tiles[6][17] = TileType::BLOCKED;
    _tiles[7][16] = TileType::BLOCKED;
    _tiles[7][17] = TileType::BLOCKED;
    // Bookshelf B at col 14, rows 5-7
    _tiles[5][14] = TileType::BLOCKED;
    _tiles[5][15] = TileType::BLOCKED;
    _tiles[6][14] = TileType::BLOCKED;
    _tiles[6][15] = TileType::BLOCKED;
    _tiles[7][14] = TileType::BLOCKED;
    _tiles[7][15] = TileType::BLOCKED;
    // Bookshelf B at col 18, rows 5-7
    _tiles[5][18] = TileType::BLOCKED;
    _tiles[5][19] = TileType::BLOCKED;
    _tiles[6][18] = TileType::BLOCKED;
    _tiles[6][19] = TileType::BLOCKED;
    _tiles[7][18] = TileType::BLOCKED;
    _tiles[7][19] = TileType::BLOCKED;
    // Seat 1 at col 17, rows 8-9
    _tiles[8][17] = TileType::BLOCKED;
    _tiles[9][17] = TileType::BLOCKED;
    // Seat 1 at col 15, rows 8-9
    _tiles[8][15] = TileType::BLOCKED;
    _tiles[9][15] = TileType::BLOCKED;
    // Seat 2 at col 15, rows 12-13
    _tiles[12][15] = TileType::BLOCKED;
    _tiles[13][15] = TileType::BLOCKED;
    // Seat 2 at col 17, rows 12-13
    _tiles[12][17] = TileType::BLOCKED;
    _tiles[13][17] = TileType::BLOCKED;
    // Seat 3 at col 13, rows 9-10
    _tiles[9][13] = TileType::BLOCKED;
    _tiles[10][13] = TileType::BLOCKED;
    // Seat 3 at col 13, rows 11-12
    _tiles[11][13] = TileType::BLOCKED;
    _tiles[12][13] = TileType::BLOCKED;
    // Seat 4 at col 19, rows 9-10
    _tiles[9][19] = TileType::BLOCKED;
    _tiles[10][19] = TileType::BLOCKED;
    // Seat 4 at col 19, rows 11-12
    _tiles[11][19] = TileType::BLOCKED;
    _tiles[12][19] = TileType::BLOCKED;
    // Plant Top G at col 14, row 7
    _tiles[7][14] = TileType::BLOCKED;
    // Plant Bottom White at col 14, row 8
    _tiles[8][14] = TileType::BLOCKED;
    // Plant Top G at col 18, row 7
    _tiles[7][18] = TileType::BLOCKED;
    // Plant Bottom White at col 18, row 8
    _tiles[8][18] = TileType::BLOCKED;
    // Plant Top 2 at col 18, row 12
    _tiles[12][18] = TileType::BLOCKED;
    // Plant Bottom White at col 18, row 13
    _tiles[13][18] = TileType::BLOCKED;
    // Plant Bottom White at col 14, row 13
    _tiles[13][14] = TileType::BLOCKED;
    // Plant Top 2 at col 14, row 12
    _tiles[12][14] = TileType::BLOCKED;
    // Bookshelf Wood 1 at col 1, rows 0-1
    _tiles[0][1] = TileType::BLOCKED;
    _tiles[0][2] = TileType::BLOCKED;
    _tiles[0][3] = TileType::BLOCKED;
    _tiles[1][1] = TileType::BLOCKED;
    _tiles[1][2] = TileType::BLOCKED;
    _tiles[1][3] = TileType::BLOCKED;
    // Bookshelf Wood 1 at col 6, rows 0-1
    _tiles[0][6] = TileType::BLOCKED;
    _tiles[0][7] = TileType::BLOCKED;
    _tiles[0][8] = TileType::BLOCKED;
    _tiles[1][6] = TileType::BLOCKED;
    _tiles[1][7] = TileType::BLOCKED;
    _tiles[1][8] = TileType::BLOCKED;
    // Bookshelf Wood 2 at col 4, rows 0-1
    _tiles[0][4] = TileType::BLOCKED;
    _tiles[0][5] = TileType::BLOCKED;
    _tiles[1][4] = TileType::BLOCKED;
    _tiles[1][5] = TileType::BLOCKED;
    // Plant Top C at col 0, row 0
    _tiles[0][0] = TileType::BLOCKED;
    // Plant Top D at col 9, row 0
    _tiles[0][9] = TileType::BLOCKED;
    // Plant Bottom Brown at col 0, row 1
    _tiles[1][0] = TileType::BLOCKED;
    // Plant Bottom Brown at col 9, row 1
    _tiles[1][9] = TileType::BLOCKED;
    // Boxes 1 at col 1, rows 1-2
    _tiles[1][1] = TileType::BLOCKED;
    _tiles[1][2] = TileType::BLOCKED;
    _tiles[2][1] = TileType::BLOCKED;
    _tiles[2][2] = TileType::BLOCKED;
    // Boxes 2 at col 4, rows 1-2
    _tiles[1][4] = TileType::BLOCKED;
    _tiles[1][5] = TileType::BLOCKED;
    _tiles[2][4] = TileType::BLOCKED;
    _tiles[2][5] = TileType::BLOCKED;
    // Box at col 6, row 2
    _tiles[2][6] = TileType::BLOCKED;
}

int OfficeState::findCharByAgentId(uint8_t agentId) const {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive && _chars[i].agentId == (int8_t)agentId) return i;
    }
    return -1;
}

int OfficeState::findFreeSeat() const {
    for (int s = 0; s < NUM_WORKSTATIONS; s++) {
        bool taken = false;
        for (int i = 0; i < MAX_AGENTS; i++) {
            if (_chars[i].alive && _chars[i].seatIdx == s) {
                taken = true;
                break;
            }
        }
        if (!taken) return s;
    }
    return -1;
}

int OfficeState::findOrAssignChar(uint8_t agentId) {
    // First: find a character already assigned to this agentId
    int existing = findCharByAgentId(agentId);
    if (existing >= 0) return existing;

    // Second: find an idle character not assigned to any agent
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive && _chars[i].agentId < 0 &&
            (_chars[i].state == CharState::IDLE || _chars[i].state == CharState::WALK)) {
            _chars[i].agentId = (int8_t)agentId;
            return i;
        }
    }
    return -1;
}

int OfficeState::getActiveAgentCount() const {
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (!_chars[i].alive) continue;
        if (_chars[i].agentId >= 0 && _chars[i].isActive) count++;
    }
    return count;
}

int OfficeState::getCharacterCount() const {
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive) count++;
    }
    return count;
}

void OfficeState::setAgentState(uint8_t id, CharState state, const char* toolName) {
    if (id >= MAX_AGENTS) return;  // Guard against int8_t truncation / -1 collision

    int idx;

    if (state == CharState::OFFLINE) {
        // Agent going offline: unassign character, walk back to zone
        idx = findCharByAgentId(id);
        if (idx < 0) return;
        Character& ch = _chars[idx];
        ch.agentId = -1;
        ch.isActive = false;
        ch.toolName[0] = '\0';
        ch.bubbleType = 0;
        ch.bubbleTimer = 0;
        // Release seat
        ch.seatIdx = -1;
        walkToZone(ch);
        return;
    }

    idx = findOrAssignChar(id);
    if (idx < 0) return;

    Character& ch = _chars[idx];

    // Store tool name
    if (toolName && toolName[0] != '\0') {
        strncpy(ch.toolName, toolName, MAX_TOOL_NAME_LEN);
        ch.toolName[MAX_TOOL_NAME_LEN] = '\0';
    } else {
        ch.toolName[0] = '\0';
    }

    ch.isActive = (state == CharState::TYPE || state == CharState::READ);

    // Determine actual animation state from protocol state
    if (state == CharState::TYPE || state == CharState::READ) {
        // Assign a seat if not already seated
        if (ch.seatIdx < 0) {
            ch.seatIdx = (int8_t)findFreeSeat();
        }
        // Active: go to desk
        if (ch.seatIdx >= 0) {
            const auto& ws = WORKSTATIONS[ch.seatIdx];
            if (ch.tileCol == ws.seatCol && ch.tileRow == ws.seatRow) {
                // Already at seat
                ch.state = isReadingTool(ch.toolName) ? CharState::READ : CharState::TYPE;
                ch.dir = ws.facingDir;
                ch.frame = 0;
                ch.frameTimer = 0;
            } else {
                // Walk to seat (cancels any current walk, e.g., walking to zone)
                startWalk(ch, (int8_t)ws.seatCol, (int8_t)ws.seatRow);
            }
        } else {
            ch.state = isReadingTool(ch.toolName) ? CharState::READ : CharState::TYPE;
            ch.frame = 0;
            ch.frameTimer = 0;
        }
    } else if (state == CharState::IDLE) {
        // Release seat if character was heading to desk or working
        if (ch.state == CharState::TYPE || ch.state == CharState::READ ||
            (ch.state == CharState::WALK && ch.seatIdx >= 0)) {
            ch.seatIdx = -1;
        }
        // Mark inactive -- updateCharacter() will handle the transition to zone walk
        ch.isActive = false;
        ch.bubbleType = 0;
        ch.bubbleTimer = 0;
    }

    // Handle bubble for special states
    if (state == CharState::TYPE && toolName && strcmp(toolName, "PERMISSION") == 0) {
        ch.bubbleType = 1; // permission
        ch.bubbleTimer = 10.0f;
    } else if (state == CharState::IDLE) {
        ch.bubbleType = 2; // waiting
        ch.bubbleTimer = 2.0f;
    } else {
        ch.bubbleType = 0;
    }
}

void OfficeState::setAgentCount(uint8_t count) {
    // Agent count is informational only -- characters are always visible
    (void)count;
}

void OfficeState::onHeartbeat() {
    _lastHeartbeatMs = millis();
    _connected = true;
}

bool OfficeState::checkHeartbeat(uint32_t nowMs) {
    if (_lastHeartbeatMs == 0) return false;
    if (nowMs - _lastHeartbeatMs > HEARTBEAT_TIMEOUT_MS) {
        _connected = false;
        return false;
    }
    return true;
}

int OfficeState::hitTestCharacter(int screenX, int screenY) const {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (!_chars[i].alive) continue;
        if (_chars[i].state == CharState::SPAWN || _chars[i].state == CharState::DESPAWN) continue;

        int sittingOffset = (_chars[i].state == CharState::TYPE || _chars[i].state == CharState::READ) ? SITTING_OFFSET_PX : 0;
        // Character center: x, y+sittingOffset shifted up by half height
        float cx = _chars[i].x;
        float cy = _chars[i].y + sittingOffset - CHAR_H / 2.0f;

        float dx = screenX - cx;
        float dy = screenY - cy;
#if defined(HAS_TOUCH)
        if (dx * dx + dy * dy <= TOUCH_CHAR_RADIUS_PX * TOUCH_CHAR_RADIUS_PX) {
            return i;
        }
#else
        (void)dx; (void)dy;
#endif
    }
    return -1;
}

void OfficeState::showInfoBubble(int agentIndex) {
    if (agentIndex < 0 || agentIndex >= MAX_AGENTS) return;
    Character& ch = _chars[agentIndex];
    if (!ch.alive) return;
    ch.bubbleType = 3;
#if defined(HAS_TOUCH)
    ch.bubbleTimer = INFO_BUBBLE_DURATION_SEC;
#else
    ch.bubbleTimer = 3.0f;
#endif
}

bool OfficeState::hitTestStatusBar(int screenY) const {
    return screenY >= SCREEN_H - STATUS_BAR_H;
}

void OfficeState::cycleStatusMode() {
    _statusMode = static_cast<StatusMode>((static_cast<uint8_t>(_statusMode) + 1) % STATUS_MODE_COUNT);
}

void OfficeState::update(float dt) {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (!_chars[i].alive) continue;
        updateCharacter(_chars[i], dt);
    }
}

void OfficeState::updateCharacter(Character& ch, float dt) {
    ch.frameTimer += dt;

    // Handle spawn/despawn effects (only used at boot if desired)
    if (ch.state == CharState::SPAWN) {
        ch.effectTimer += dt;
        if (ch.effectTimer >= SPAWN_DURATION_SEC) {
            ch.state = CharState::IDLE;
            ch.frame = 0;
            ch.frameTimer = 0;
        }
        return;
    }

    if (ch.state == CharState::DESPAWN) {
        ch.effectTimer += dt;
        if (ch.effectTimer >= SPAWN_DURATION_SEC) {
            // Characters never truly despawn -- transition to idle in zone
            ch.state = CharState::IDLE;
            ch.frame = 0;
            ch.frameTimer = 0;
        }
        return;
    }

    switch (ch.state) {
        case CharState::TYPE:
        case CharState::READ: {
            if (ch.frameTimer >= TYPE_FRAME_DURATION_SEC) {
                ch.frameTimer -= TYPE_FRAME_DURATION_SEC;
                ch.frame = (ch.frame + 1) % 2;
            }
            if (!ch.isActive) {
                ch.state = CharState::IDLE;
                ch.frame = 0;
                ch.frameTimer = 0;
                ch.bubbleType = 0;
                ch.bubbleTimer = 0;
                ch.seatIdx = -1;
                walkToZone(ch);
            }
            break;
        }

        case CharState::IDLE: {
            ch.frame = 0;

            // If became active, go to seat
            if (ch.isActive && ch.seatIdx >= 0) {
                const auto& ws = WORKSTATIONS[ch.seatIdx];
                if (ch.tileCol == ws.seatCol && ch.tileRow == ws.seatRow) {
                    ch.state = CharState::TYPE;
                    ch.dir = ws.facingDir;
                } else {
                    startWalk(ch, (int8_t)ws.seatCol, (int8_t)ws.seatRow);
                }
                ch.frame = 0;
                ch.frameTimer = 0;
                break;
            }

            // Wander timer
            ch.wanderTimer -= dt;
            if (ch.wanderTimer <= 0) {
                // Unassigned characters wander within their home zone
                if (ch.agentId < 0) {
                    startZoneWander(ch);
                } else {
                    startWander(ch);
                }
                ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
            }
            break;
        }

        case CharState::WALK: {
            // Walk animation
            if (ch.frameTimer >= WALK_FRAME_DURATION_SEC) {
                ch.frameTimer -= WALK_FRAME_DURATION_SEC;
                ch.frame = (ch.frame + 1) % 4;
            }

            if (ch.pathIdx >= ch.pathLen) {
                // Path complete
                float cx = ch.tileCol * TILE_SIZE + TILE_SIZE / 2.0f;
                float cy = ch.tileRow * TILE_SIZE + TILE_SIZE / 2.0f;
                ch.x = cx;
                ch.y = cy;

                if (ch.isActive && ch.seatIdx >= 0) {
                    const auto& ws = WORKSTATIONS[ch.seatIdx];
                    if (ch.tileCol == ws.seatCol && ch.tileRow == ws.seatRow) {
                        ch.state = isReadingTool(ch.toolName) ? CharState::READ : CharState::TYPE;
                        ch.dir = ws.facingDir;
                    } else {
                        ch.state = CharState::IDLE;
                    }
                } else {
                    ch.state = CharState::IDLE;
                    ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
                }
                ch.frame = 0;
                ch.frameTimer = 0;
                break;
            }

            // Move toward next tile
            PathNode next = ch.path[ch.pathIdx];

            // Update direction
            int dc = next.col - ch.tileCol;
            int dr = next.row - ch.tileRow;
            if (dc > 0) ch.dir = Dir::RIGHT;
            else if (dc < 0) ch.dir = Dir::LEFT;
            else if (dr > 0) ch.dir = Dir::DOWN;
            else ch.dir = Dir::UP;

            ch.moveProgress += (WALK_SPEED_PX_PER_SEC / TILE_SIZE) * dt;

            float fromX = ch.tileCol * TILE_SIZE + TILE_SIZE / 2.0f;
            float fromY = ch.tileRow * TILE_SIZE + TILE_SIZE / 2.0f;
            float toX = next.col * TILE_SIZE + TILE_SIZE / 2.0f;
            float toY = next.row * TILE_SIZE + TILE_SIZE / 2.0f;

            float t = ch.moveProgress;
            if (t > 1.0f) t = 1.0f;
            ch.x = fromX + (toX - fromX) * t;
            ch.y = fromY + (toY - fromY) * t;

            if (ch.moveProgress >= 1.0f) {
                ch.tileCol = next.col;
                ch.tileRow = next.row;
                ch.x = toX;
                ch.y = toY;
                ch.pathIdx++;
                ch.moveProgress = 0;
            }
            break;
        }

        default:
            break;
    }

    // Tick bubble timer
    if (ch.bubbleType > 0 && ch.bubbleTimer > 0) {
        ch.bubbleTimer -= dt;
        if (ch.bubbleTimer <= 0) {
            ch.bubbleType = 0;
            ch.bubbleTimer = 0;
        }
    }
}

void OfficeState::startWalk(Character& ch, int8_t goalCol, int8_t goalRow) {
    PathNode pathBuf[64];
    uint8_t pathLen = 0;
    if (findPath(ch.tileCol, ch.tileRow, goalCol, goalRow, pathBuf, pathLen)) {
        memcpy(ch.path, pathBuf, pathLen * sizeof(PathNode));
        ch.pathLen = pathLen;
        ch.pathIdx = 0;
        ch.moveProgress = 0;
        ch.state = CharState::WALK;
        ch.frame = 0;
        ch.frameTimer = 0;
    }
}

void OfficeState::startWander(Character& ch) {
    // Pick a random walkable tile anywhere
    for (int attempt = 0; attempt < 20; attempt++) {
        int8_t col = (int8_t)randomInt(1, GRID_COLS - 2);
        int8_t row = (int8_t)randomInt(1, GRID_ROWS - 1);
        if (isWalkable(col, row)) {
            startWalk(ch, col, row);
            ch.wanderCount++;
            return;
        }
    }
}

void OfficeState::startZoneWander(Character& ch) {
    int colMin, colMax, rowMin, rowMax;
    if (ch.homeZone == SocialZone::BREAK_ROOM) {
        colMin = ZONE_BREAK_COL_MIN; colMax = ZONE_BREAK_COL_MAX;
        rowMin = ZONE_BREAK_ROW_MIN; rowMax = ZONE_BREAK_ROW_MAX;
    } else {
        colMin = ZONE_LIB_COL_MIN; colMax = ZONE_LIB_COL_MAX;
        rowMin = ZONE_LIB_ROW_MIN; rowMax = ZONE_LIB_ROW_MAX;
    }

    for (int attempt = 0; attempt < 30; attempt++) {
        int8_t col = (int8_t)randomInt(colMin, colMax);
        int8_t row = (int8_t)randomInt(rowMin, rowMax);
        if (isWalkable(col, row)) {
            startWalk(ch, col, row);
            ch.wanderCount++;
            return;
        }
    }
}

void OfficeState::walkToZone(Character& ch) {
    int colMin, colMax, rowMin, rowMax;
    if (ch.homeZone == SocialZone::BREAK_ROOM) {
        colMin = ZONE_BREAK_COL_MIN; colMax = ZONE_BREAK_COL_MAX;
        rowMin = ZONE_BREAK_ROW_MIN; rowMax = ZONE_BREAK_ROW_MAX;
    } else {
        colMin = ZONE_LIB_COL_MIN; colMax = ZONE_LIB_COL_MAX;
        rowMin = ZONE_LIB_ROW_MIN; rowMax = ZONE_LIB_ROW_MAX;
    }

    // Try random tiles in zone
    for (int attempt = 0; attempt < 30; attempt++) {
        int8_t col = (int8_t)randomInt(colMin, colMax);
        int8_t row = (int8_t)randomInt(rowMin, rowMax);
        if (isWalkable(col, row)) {
            startWalk(ch, col, row);
            return;
        }
    }

    // Fallback: scan zone for any walkable tile
    for (int r = rowMin; r <= rowMax; r++) {
        for (int c = colMin; c <= colMax; c++) {
            if (isWalkable((int8_t)c, (int8_t)r)) {
                startWalk(ch, (int8_t)c, (int8_t)r);
                return;
            }
        }
    }

    // If no walkable tile in zone, just go idle where we are
    ch.state = CharState::IDLE;
    ch.frame = 0;
    ch.frameTimer = 0;
    ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
}

void OfficeState::snapToSeat(Character& ch) {
    if (ch.seatIdx < 0) return;
    const auto& ws = WORKSTATIONS[ch.seatIdx];
    ch.tileCol = (int8_t)ws.seatCol;
    ch.tileRow = (int8_t)ws.seatRow;
    ch.x = ws.seatCol * TILE_SIZE + TILE_SIZE / 2.0f;
    ch.y = ws.seatRow * TILE_SIZE + TILE_SIZE / 2.0f;
    ch.dir = ws.facingDir;
}

bool OfficeState::isWalkable(int8_t col, int8_t row) const {
    if (col < 0 || col >= GRID_COLS || row < 0 || row >= GRID_ROWS) return false;
    return _tiles[row][col] == TileType::FLOOR;
}

// BFS pathfinding
bool OfficeState::findPath(int8_t fromCol, int8_t fromRow, int8_t toCol, int8_t toRow,
                           PathNode* outPath, uint8_t& outLen) {
    if (fromCol == toCol && fromRow == toRow) {
        outLen = 0;
        return true;
    }

    // BFS with parent tracking
    static const int8_t DX[] = {0, 0, 1, -1};
    static const int8_t DY[] = {1, -1, 0, 0};

    bool visited[GRID_ROWS][GRID_COLS];
    int8_t parentCol[GRID_ROWS][GRID_COLS];
    int8_t parentRow[GRID_ROWS][GRID_COLS];
    memset(visited, 0, sizeof(visited));
    memset(parentCol, -1, sizeof(parentCol));
    memset(parentRow, -1, sizeof(parentRow));

    // BFS queue (fixed size)
    struct QNode { int8_t col, row; };
    QNode queue[GRID_ROWS * GRID_COLS];
    int qHead = 0, qTail = 0;

    visited[fromRow][fromCol] = true;
    queue[qTail++] = {fromCol, fromRow};

    bool found = false;
    while (qHead < qTail) {
        QNode cur = queue[qHead++];

        if (cur.col == toCol && cur.row == toRow) {
            found = true;
            break;
        }

        for (int d = 0; d < 4; d++) {
            int8_t nc = cur.col + DX[d];
            int8_t nr = cur.row + DY[d];
            if (nc < 0 || nc >= GRID_COLS || nr < 0 || nr >= GRID_ROWS) continue;
            if (visited[nr][nc]) continue;
            // Allow walking to destination even if it's "blocked" (e.g., seat tile)
            if (!isWalkable(nc, nr) && !(nc == toCol && nr == toRow)) continue;
            if (qTail >= GRID_ROWS * GRID_COLS) break;
            visited[nr][nc] = true;
            parentCol[nr][nc] = cur.col;
            parentRow[nr][nc] = cur.row;
            queue[qTail++] = {nc, nr};
        }
    }

    if (!found) {
        outLen = 0;
        return false;
    }

    // Reconstruct path (reverse)
    PathNode revPath[64];
    int len = 0;
    int8_t cc = toCol, cr = toRow;
    while (cc != fromCol || cr != fromRow) {
        if (len >= 64) { outLen = 0; return false; }
        revPath[len++] = {cc, cr};
        int8_t pc = parentCol[cr][cc];
        int8_t pr = parentRow[cr][cc];
        cc = pc;
        cr = pr;
    }

    // Reverse into output
    outLen = (uint8_t)len;
    for (int i = 0; i < len; i++) {
        outPath[i] = revPath[len - 1 - i];
    }
    return true;
}

float OfficeState::randomRange(float minVal, float maxVal) {
    return minVal + ((float)random(10000) / 10000.0f) * (maxVal - minVal);
}

int OfficeState::randomInt(int minVal, int maxVal) {
    return minVal + random(maxVal - minVal + 1);
}

void OfficeState::setUsageStats(uint8_t curPct, uint8_t wkPct, uint16_t curResetMin, uint16_t wkResetMin) {
    _usage.currentPct = curPct > 100 ? 100 : curPct;
    _usage.weeklyPct = wkPct > 100 ? 100 : wkPct;
    _usage.currentResetMin = curResetMin;
    _usage.weeklyResetMin = wkResetMin;
    _usage.valid = true;
}
