#include "office_state.h"
#include <Arduino.h>
#include <Preferences.h>
#include <string.h>

// ── Reading tools (show reading animation instead of typing) ──
static bool isReadingTool(const char* tool) {
    if (!tool || tool[0] == '\0') return false;
    return (strcmp(tool, "Read") == 0 || strcmp(tool, "Grep") == 0 ||
            strcmp(tool, "Glob") == 0 || strcmp(tool, "WebFetch") == 0 ||
            strcmp(tool, "WebSearch") == 0);
}

void OfficeState::init() {
    memset(_chars, 0, sizeof(_chars));
    for (int i = 0; i < MAX_AGENTS; i++) {
        _chars[i].alive = false;
        _chars[i].seatIdx = -1;
        _chars[i].agentId = -1;
    }
    initTileMap();
    _connected = false;
    _lastHeartbeatMs = 0;
    loadSettings();
}

void OfficeState::spawnAllCharacters() {
    for (int i = 0; i < MAX_AGENTS; i++) {
        Character& ch = _chars[i];
        memset(&ch, 0, sizeof(Character));
        ch.alive = true;
        ch.id = (uint8_t)i;
        ch.palette = (uint8_t)(i % NUM_PALETTES);
        ch.state = CharState::IDLE;
        ch.isActive = false;
        ch.seatIdx = -1;
        ch.agentId = -1;
        ch.homeZone = (i < 3) ? SocialZone::BREAK_ROOM : SocialZone::LIBRARY;
        ch.dir = Dir::DOWN;
        ch.frame = 0;
        ch.frameTimer = 0;
        ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
        ch.wanderCount = 0;
        ch.wanderLimit = (uint8_t)randomInt(WANDER_MOVES_MIN, WANDER_MOVES_MAX);
        ch.pathLen = 0;
        ch.pathIdx = 0;
        ch.idleActivity = IdleActivity::NONE;
        ch.activityDir = Dir::DOWN;
        ch.activityTimer = 0;
        ch.activityCooldown = false;
        ch.bubbleType = 0;
        ch.bubbleTimer = 0;
        ch.effectTimer = 0;
        ch.toolName[0] = '\0';

        // Place at a random walkable tile within home zone
        int colMin, colMax, rowMin, rowMax;
        if (ch.homeZone == SocialZone::BREAK_ROOM) {
            colMin = ZONE_BREAK_COL_MIN; colMax = ZONE_BREAK_COL_MAX;
            rowMin = ZONE_BREAK_ROW_MIN; rowMax = ZONE_BREAK_ROW_MAX;
        } else {
            colMin = ZONE_LIB_COL_MIN; colMax = ZONE_LIB_COL_MAX;
            rowMin = ZONE_LIB_ROW_MIN; rowMax = ZONE_LIB_ROW_MAX;
        }

        bool placed = false;
        for (int attempt = 0; attempt < 40; attempt++) {
            int8_t col = (int8_t)randomInt(colMin, colMax);
            int8_t row = (int8_t)randomInt(rowMin, rowMax);
            if (isWalkable(col, row)) {
                ch.tileCol = col;
                ch.tileRow = row;
                ch.x = col * TILE_SIZE + TILE_SIZE / 2.0f;
                ch.y = row * TILE_SIZE + TILE_SIZE / 2.0f;
                placed = true;
                break;
            }
        }
        if (!placed) {
            // Fallback: scan zone for any walkable tile
            for (int r = rowMin; r <= rowMax && !placed; r++) {
                for (int c = colMin; c <= colMax && !placed; c++) {
                    if (isWalkable((int8_t)c, (int8_t)r)) {
                        ch.tileCol = (int8_t)c;
                        ch.tileRow = (int8_t)r;
                        ch.x = c * TILE_SIZE + TILE_SIZE / 2.0f;
                        ch.y = r * TILE_SIZE + TILE_SIZE / 2.0f;
                        placed = true;
                    }
                }
            }
        }
        if (!placed) {
            // Last resort: center of map
            ch.tileCol = 10;
            ch.tileRow = 3;
            ch.x = 10 * TILE_SIZE + TILE_SIZE / 2.0f;
            ch.y = 3 * TILE_SIZE + TILE_SIZE / 2.0f;
        }
    }

    initPet();
}

// Generated by tools/layout_editor.html
void OfficeState::initTileMap() {
    // Initialize all tiles
    for (int r = 0; r < GRID_ROWS; r++) {
        for (int c = 0; c < GRID_COLS; c++) {
            _tiles[r][c] = TileType::FLOOR;
        }
    }
    // Mark desk tiles as blocked (2x2 desks)
    for (int i = 0; i < NUM_WORKSTATIONS; i++) {
        const auto& ws = WORKSTATIONS[i];
        for (int dr = 0; dr < 2; dr++) {
            for (int dc = 0; dc < 2; dc++) {
                int r = ws.deskRow + dr;
                int c = ws.deskCol + dc;
                if (r >= 0 && r < GRID_ROWS && c >= 0 && c < GRID_COLS) {
                    _tiles[r][c] = TileType::BLOCKED;
                }
            }
        }
    }
    // Mark decorative furniture as blocked
    // Water Cooler at col 12, rows 0-2
    _tiles[0][12] = TileType::BLOCKED;
    _tiles[1][12] = TileType::BLOCKED;
    _tiles[2][12] = TileType::BLOCKED;
    // Counter Top at col 16, row 1
    _tiles[1][16] = TileType::BLOCKED;
    _tiles[1][17] = TileType::BLOCKED;
    // Counter Top at col 14, row 1
    _tiles[1][14] = TileType::BLOCKED;
    _tiles[1][15] = TileType::BLOCKED;
    // Counter Bottom A at col 14, row 2
    _tiles[2][14] = TileType::BLOCKED;
    _tiles[2][15] = TileType::BLOCKED;
    // Counter Bottom A at col 16, row 2
    _tiles[2][16] = TileType::BLOCKED;
    _tiles[2][17] = TileType::BLOCKED;
    // Coffee Maker at col 16, rows 0-1
    _tiles[0][16] = TileType::BLOCKED;
    _tiles[1][16] = TileType::BLOCKED;
    // Coffee Maker at col 17, rows 0-1
    _tiles[0][17] = TileType::BLOCKED;
    _tiles[1][17] = TileType::BLOCKED;
    // Vending Machine at col 18, rows 0-2
    _tiles[0][18] = TileType::BLOCKED;
    _tiles[0][19] = TileType::BLOCKED;
    _tiles[1][18] = TileType::BLOCKED;
    _tiles[1][19] = TileType::BLOCKED;
    _tiles[2][18] = TileType::BLOCKED;
    _tiles[2][19] = TileType::BLOCKED;
    // Plant Top E at col 13, row 1
    _tiles[1][13] = TileType::BLOCKED;
    // Plant Bottom White at col 13, row 2
    _tiles[2][13] = TileType::BLOCKED;
    // Computer E at col 1, row 12
    _tiles[12][1] = TileType::BLOCKED;
    _tiles[12][2] = TileType::BLOCKED;
    _tiles[12][3] = TileType::BLOCKED;
    // Computer G at col 7, row 12
    _tiles[12][7] = TileType::BLOCKED;
    // Laptop B at col 2, rows 6-7
    _tiles[6][2] = TileType::BLOCKED;
    _tiles[7][2] = TileType::BLOCKED;
    // Computer B at col 7, rows 6-7
    _tiles[6][7] = TileType::BLOCKED;
    _tiles[6][8] = TileType::BLOCKED;
    _tiles[7][7] = TileType::BLOCKED;
    _tiles[7][8] = TileType::BLOCKED;
    // Plant Bottom Brown at col 9, row 13
    _tiles[13][9] = TileType::BLOCKED;
    // Plant Bottom Brown at col 0, row 13
    _tiles[13][0] = TileType::BLOCKED;
    // Plant Top C at col 0, row 12
    _tiles[12][0] = TileType::BLOCKED;
    // Plant Top D at col 9, row 12
    _tiles[12][9] = TileType::BLOCKED;
    // Bookshelf A at col 12, rows 5-7
    _tiles[5][12] = TileType::BLOCKED;
    _tiles[5][13] = TileType::BLOCKED;
    _tiles[6][12] = TileType::BLOCKED;
    _tiles[6][13] = TileType::BLOCKED;
    _tiles[7][12] = TileType::BLOCKED;
    _tiles[7][13] = TileType::BLOCKED;
    // Bookshelf A at col 16, rows 5-7
    _tiles[5][16] = TileType::BLOCKED;
    _tiles[5][17] = TileType::BLOCKED;
    _tiles[6][16] = TileType::BLOCKED;
    _tiles[6][17] = TileType::BLOCKED;
    _tiles[7][16] = TileType::BLOCKED;
    _tiles[7][17] = TileType::BLOCKED;
    // Bookshelf B at col 14, rows 5-7
    _tiles[5][14] = TileType::BLOCKED;
    _tiles[5][15] = TileType::BLOCKED;
    _tiles[6][14] = TileType::BLOCKED;
    _tiles[6][15] = TileType::BLOCKED;
    _tiles[7][14] = TileType::BLOCKED;
    _tiles[7][15] = TileType::BLOCKED;
    // Bookshelf B at col 18, rows 5-7
    _tiles[5][18] = TileType::BLOCKED;
    _tiles[5][19] = TileType::BLOCKED;
    _tiles[6][18] = TileType::BLOCKED;
    _tiles[6][19] = TileType::BLOCKED;
    _tiles[7][18] = TileType::BLOCKED;
    _tiles[7][19] = TileType::BLOCKED;
    // Plant Top G at col 11, row 5
    _tiles[5][11] = TileType::BLOCKED;
    // Plant Bottom White at col 11, row 6
    _tiles[6][11] = TileType::BLOCKED;
    // Plant Top 2 at col 18, row 12
    _tiles[12][18] = TileType::BLOCKED;
    // Plant Bottom White at col 18, row 13
    _tiles[13][18] = TileType::BLOCKED;
    // Plant Bottom White at col 14, row 13
    _tiles[13][14] = TileType::BLOCKED;
    // Plant Top 2 at col 14, row 12
    _tiles[12][14] = TileType::BLOCKED;
    // Bookshelf Wood 1 at col 1, rows 0-1
    _tiles[0][1] = TileType::BLOCKED;
    _tiles[0][2] = TileType::BLOCKED;
    _tiles[0][3] = TileType::BLOCKED;
    _tiles[1][1] = TileType::BLOCKED;
    _tiles[1][2] = TileType::BLOCKED;
    _tiles[1][3] = TileType::BLOCKED;
    // Bookshelf Wood 1 at col 6, rows 0-1
    _tiles[0][6] = TileType::BLOCKED;
    _tiles[0][7] = TileType::BLOCKED;
    _tiles[0][8] = TileType::BLOCKED;
    _tiles[1][6] = TileType::BLOCKED;
    _tiles[1][7] = TileType::BLOCKED;
    _tiles[1][8] = TileType::BLOCKED;
    // Bookshelf Wood 2 at col 4, rows 0-1
    _tiles[0][4] = TileType::BLOCKED;
    _tiles[0][5] = TileType::BLOCKED;
    _tiles[1][4] = TileType::BLOCKED;
    _tiles[1][5] = TileType::BLOCKED;
    // Plant Top C at col 0, row 0
    _tiles[0][0] = TileType::BLOCKED;
    // Plant Top D at col 9, row 0
    _tiles[0][9] = TileType::BLOCKED;
    // Plant Bottom Brown at col 0, row 1
    _tiles[1][0] = TileType::BLOCKED;
    // Plant Bottom Brown at col 9, row 1
    _tiles[1][9] = TileType::BLOCKED;
    // Table at col 19, rows 3-4
    _tiles[3][19] = TileType::BLOCKED;
    _tiles[4][19] = TileType::BLOCKED;
    // Laptop C at col 6, rows 4-5
    _tiles[4][6] = TileType::BLOCKED;
    _tiles[5][6] = TileType::BLOCKED;
    // Laptop D at col 3, rows 4-5
    _tiles[4][3] = TileType::BLOCKED;
    _tiles[5][3] = TileType::BLOCKED;
    // Box at col 8, row 3
    _tiles[3][8] = TileType::BLOCKED;
    // Boxes 2 at col 6, rows 2-3
    _tiles[2][6] = TileType::BLOCKED;
    _tiles[2][7] = TileType::BLOCKED;
    _tiles[3][6] = TileType::BLOCKED;
    _tiles[3][7] = TileType::BLOCKED;
    // Boxes 1 at col 1, rows 2-3
    _tiles[2][1] = TileType::BLOCKED;
    _tiles[2][2] = TileType::BLOCKED;
    _tiles[3][1] = TileType::BLOCKED;
    _tiles[3][2] = TileType::BLOCKED;
    // Plant Top H at col 11, row 6
    _tiles[6][11] = TileType::BLOCKED;
    // Plant Bottom White at col 11, row 7
    _tiles[7][11] = TileType::BLOCKED;
    // Microwave at col 14, row 1
    _tiles[1][14] = TileType::BLOCKED;
    _tiles[1][15] = TileType::BLOCKED;
    // Trash at col 11, rows 1-2
    _tiles[1][11] = TileType::BLOCKED;
    _tiles[2][11] = TileType::BLOCKED;
}

int OfficeState::findCharByAgentId(uint8_t agentId) const {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive && _chars[i].agentId == (int8_t)agentId) return i;
    }
    return -1;
}

int OfficeState::findFreeSeat() const {
    for (int s = 0; s < NUM_WORKSTATIONS; s++) {
        bool taken = false;
        for (int i = 0; i < MAX_AGENTS; i++) {
            if (_chars[i].alive && _chars[i].seatIdx == s) {
                taken = true;
                break;
            }
        }
        if (!taken) return s;
    }
    return -1;
}

int OfficeState::findOrAssignChar(uint8_t agentId) {
    // First: find a character already assigned to this agentId
    int existing = findCharByAgentId(agentId);
    if (existing >= 0) return existing;

    // Second: find an idle character not assigned to any agent
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive && _chars[i].agentId < 0 &&
            (_chars[i].state == CharState::IDLE || _chars[i].state == CharState::WALK ||
             _chars[i].state == CharState::ACTIVITY)) {
            _chars[i].agentId = (int8_t)agentId;
            return i;
        }
    }
    return -1;
}

int OfficeState::getActiveAgentCount() const {
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (!_chars[i].alive) continue;
        if (_chars[i].agentId >= 0 && _chars[i].isActive) count++;
    }
    return count;
}

int OfficeState::getCharacterCount() const {
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive) count++;
    }
    return count;
}

void OfficeState::setAgentState(uint8_t id, CharState state, const char* toolName) {
    if (id > MAX_AGENT_ID) return;  // int8_t storage: IDs above 127 wrap negative, colliding with -1 sentinel

    int idx;

    if (state == CharState::OFFLINE) {
        // Agent going offline: unassign character, walk back to zone
        idx = findCharByAgentId(id);
        if (idx < 0) return;
        Character& ch = _chars[idx];
        ch.agentId = -1;
        ch.isActive = false;
        ch.toolName[0] = '\0';
        ch.bubbleType = 0;
        ch.bubbleTimer = 0;
        ch.idleActivity = IdleActivity::NONE;
        ch.activityTimer = 0;
        ch.activityCooldown = false;
        ch.hasPlayedJobSound = false;
        // Release seat
        ch.seatIdx = -1;
        walkToZone(ch);
        return;
    }

    idx = findOrAssignChar(id);
    if (idx < 0) return;

    Character& ch = _chars[idx];

    // Clear any idle activity state (agent preemption)
    ch.idleActivity = IdleActivity::NONE;
    ch.activityTimer = 0;
    ch.activityCooldown = false;

    // Store tool name
    if (toolName && toolName[0] != '\0') {
        strncpy(ch.toolName, toolName, MAX_TOOL_NAME_LEN);
        ch.toolName[MAX_TOOL_NAME_LEN] = '\0';
    } else {
        ch.toolName[0] = '\0';
    }

    ch.isActive = (state == CharState::TYPE || state == CharState::READ);

    // Queue typing sound on first TYPE transition in this job
    if (state == CharState::TYPE && !ch.hasPlayedJobSound) {
        ch.hasPlayedJobSound = true;
        queueSound(SoundId::KEYBOARD_TYPE);
    }

    // Determine actual animation state from protocol state
    if (state == CharState::TYPE || state == CharState::READ) {
        // Assign a seat if not already seated
        if (ch.seatIdx < 0) {
            ch.seatIdx = (int8_t)findFreeSeat();
        }
        // Active: go to desk
        if (ch.seatIdx >= 0) {
            const auto& ws = WORKSTATIONS[ch.seatIdx];
            if (ch.tileCol == ws.seatCol && ch.tileRow == ws.seatRow) {
                // Already at seat
                ch.state = isReadingTool(ch.toolName) ? CharState::READ : CharState::TYPE;
                ch.dir = ws.facingDir;
                ch.frame = 0;
                ch.frameTimer = 0;
            } else {
                // Walk to seat (cancels any current walk, e.g., walking to zone)
                startWalk(ch, (int8_t)ws.seatCol, (int8_t)ws.seatRow);
            }
        } else {
            ch.state = isReadingTool(ch.toolName) ? CharState::READ : CharState::TYPE;
            ch.frame = 0;
            ch.frameTimer = 0;
        }
    } else if (state == CharState::IDLE) {
        // Release seat if character was heading to desk or working
        if (ch.state == CharState::TYPE || ch.state == CharState::READ ||
            (ch.state == CharState::WALK && ch.seatIdx >= 0)) {
            ch.seatIdx = -1;
        }
        // Mark inactive -- updateCharacter() will handle the transition to zone walk
        ch.isActive = false;
        ch.hasPlayedJobSound = false;
        ch.bubbleType = 0;
        ch.bubbleTimer = 0;
    }

    // Handle bubble for special states
    if (state == CharState::TYPE && toolName && strcmp(toolName, "PERMISSION") == 0) {
        ch.bubbleType = 1; // permission
        ch.bubbleTimer = PERMISSION_BUBBLE_DURATION_SEC;
        queueSound(SoundId::MINIMAL_POP);
    } else if (state == CharState::IDLE) {
        ch.bubbleType = 2; // waiting
        ch.bubbleTimer = WAITING_BUBBLE_DURATION_SEC;
        queueSound(SoundId::NOTIFICATION_CLICK);
    } else {
        ch.bubbleType = 0;
    }
}

void OfficeState::setAgentCount(uint8_t count) {
    // Agent count is informational only -- characters are always visible
    (void)count;
}

void OfficeState::onHeartbeat() {
    _lastHeartbeatMs = millis();
    _connected = true;
}

bool OfficeState::checkHeartbeat(uint32_t nowMs) {
    if (_lastHeartbeatMs == 0) return false;
    if (nowMs - _lastHeartbeatMs > HEARTBEAT_TIMEOUT_MS) {
        if (_connected) {
            _connected = false;
            for (int i = 0; i < MAX_AGENTS; i++) {
                _chars[i].bubbleType = 0;
                _chars[i].bubbleTimer = 0;
            }
        }
        return false;
    }
    return true;
}

int OfficeState::hitTestCharacter(int screenX, int screenY) const {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (!_chars[i].alive) continue;
        if (_chars[i].state == CharState::SPAWN || _chars[i].state == CharState::DESPAWN) continue;

        int sittingOffset = (_chars[i].state == CharState::TYPE || _chars[i].state == CharState::READ) ? SITTING_OFFSET_PX : 0;
        // Character center: x, y+sittingOffset shifted up by half height
        float cx = _chars[i].x;
        float cy = _chars[i].y + sittingOffset - CHAR_H / 2.0f;

        float dx = screenX - cx;
        float dy = screenY - cy;
#if defined(HAS_TOUCH)
        if (dx * dx + dy * dy <= TOUCH_CHAR_RADIUS_PX * TOUCH_CHAR_RADIUS_PX) {
            return i;
        }
#else
        (void)dx; (void)dy;
#endif
    }
    return -1;
}

void OfficeState::showInfoBubble(int agentIndex) {
    if (agentIndex < 0 || agentIndex >= MAX_AGENTS) return;
    Character& ch = _chars[agentIndex];
    if (!ch.alive) return;
    ch.bubbleType = 3;
#if defined(HAS_TOUCH)
    ch.bubbleTimer = INFO_BUBBLE_DURATION_SEC;
#else
    ch.bubbleTimer = 3.0f;
#endif
}

bool OfficeState::hitTestStatusBar(int screenY) const {
    return screenY >= SCREEN_H - STATUS_BAR_H;
}

void OfficeState::cycleStatusMode() {
    _statusMode = static_cast<StatusMode>((static_cast<uint8_t>(_statusMode) + 1) % STATUS_MODE_COUNT);
}

void OfficeState::update(float dt) {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (!_chars[i].alive) continue;
        updateCharacter(_chars[i], dt);
    }
    if (_dogSettings.enabled) {
        updatePet(dt);
    }
}

void OfficeState::updateCharacter(Character& ch, float dt) {
    ch.frameTimer += dt;

    // Handle spawn/despawn effects (only used at boot if desired)
    if (ch.state == CharState::SPAWN) {
        ch.effectTimer += dt;
        if (ch.effectTimer >= SPAWN_DURATION_SEC) {
            ch.state = CharState::IDLE;
            ch.frame = 0;
            ch.frameTimer = 0;
        }
        return;
    }

    if (ch.state == CharState::DESPAWN) {
        ch.effectTimer += dt;
        if (ch.effectTimer >= SPAWN_DURATION_SEC) {
            // Characters never truly despawn -- transition to idle in zone
            ch.state = CharState::IDLE;
            ch.frame = 0;
            ch.frameTimer = 0;
        }
        return;
    }

    switch (ch.state) {
        case CharState::TYPE:
        case CharState::READ: {
            if (ch.frameTimer >= TYPE_FRAME_DURATION_SEC) {
                ch.frameTimer -= TYPE_FRAME_DURATION_SEC;
                ch.frame = (ch.frame + 1) % 2;
            }
            if (!ch.isActive) {
                ch.state = CharState::IDLE;
                ch.frame = 0;
                ch.frameTimer = 0;
                if (ch.bubbleType == 0) {
                    ch.bubbleType = 2; // waiting
                    ch.bubbleTimer = WAITING_BUBBLE_DURATION_SEC;
                }
                ch.seatIdx = -1;
                walkToZone(ch);
            }
            break;
        }

        case CharState::IDLE: {
            ch.frame = 0;

            // If became active, go to seat
            if (ch.isActive && ch.seatIdx >= 0) {
                const auto& ws = WORKSTATIONS[ch.seatIdx];
                if (ch.tileCol == ws.seatCol && ch.tileRow == ws.seatRow) {
                    ch.state = CharState::TYPE;
                    ch.dir = ws.facingDir;
                } else {
                    startWalk(ch, (int8_t)ws.seatCol, (int8_t)ws.seatRow);
                }
                ch.frame = 0;
                ch.frameTimer = 0;
                break;
            }

            // Wander timer
            ch.wanderTimer -= dt;
            if (ch.wanderTimer <= 0) {
                // Unassigned characters may do idle activities or wander in zone
                if (ch.agentId < 0) {
                    if (!ch.activityCooldown && randomRange(0, 1.0f) < ACTIVITY_CHANCE) {
                        startIdleActivity(ch);
                    } else {
                        startZoneWander(ch);
                        ch.activityCooldown = false;  // cooldown served
                    }
                } else {
                    startWander(ch);
                }
                ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
            }
            break;
        }

        case CharState::WALK: {
            // Walk animation
            if (ch.frameTimer >= WALK_FRAME_DURATION_SEC) {
                ch.frameTimer -= WALK_FRAME_DURATION_SEC;
                ch.frame = (ch.frame + 1) % 4;
            }

            if (ch.pathIdx >= ch.pathLen) {
                // Path complete
                float cx = ch.tileCol * TILE_SIZE + TILE_SIZE / 2.0f;
                float cy = ch.tileRow * TILE_SIZE + TILE_SIZE / 2.0f;
                ch.x = cx;
                ch.y = cy;

                if (ch.isActive && ch.seatIdx >= 0) {
                    const auto& ws = WORKSTATIONS[ch.seatIdx];
                    if (ch.tileCol == ws.seatCol && ch.tileRow == ws.seatRow) {
                        ch.state = isReadingTool(ch.toolName) ? CharState::READ : CharState::TYPE;
                        ch.dir = ws.facingDir;
                    } else {
                        ch.state = CharState::IDLE;
                    }
                } else if (ch.idleActivity != IdleActivity::NONE) {
                    // Arrived at activity destination — restore intended facing direction
                    ch.state = CharState::ACTIVITY;
                    ch.dir = ch.activityDir;
                    ch.activityTimer = randomRange(ACTIVITY_DURATION_MIN_SEC, ACTIVITY_DURATION_MAX_SEC);
                    ch.frame = 0;
                    ch.frameTimer = 0;
                } else {
                    ch.state = CharState::IDLE;
                    ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
                }
                ch.frame = 0;
                ch.frameTimer = 0;
                break;
            }

            // Move toward next tile
            PathNode next = ch.path[ch.pathIdx];

            // Update direction
            int dc = next.col - ch.tileCol;
            int dr = next.row - ch.tileRow;
            if (dc > 0) ch.dir = Dir::RIGHT;
            else if (dc < 0) ch.dir = Dir::LEFT;
            else if (dr > 0) ch.dir = Dir::DOWN;
            else ch.dir = Dir::UP;

            ch.moveProgress += (WALK_SPEED_PX_PER_SEC / TILE_SIZE) * dt;

            float fromX = ch.tileCol * TILE_SIZE + TILE_SIZE / 2.0f;
            float fromY = ch.tileRow * TILE_SIZE + TILE_SIZE / 2.0f;
            float toX = next.col * TILE_SIZE + TILE_SIZE / 2.0f;
            float toY = next.row * TILE_SIZE + TILE_SIZE / 2.0f;

            float t = ch.moveProgress;
            if (t > 1.0f) t = 1.0f;
            ch.x = fromX + (toX - fromX) * t;
            ch.y = fromY + (toY - fromY) * t;

            if (ch.moveProgress >= 1.0f) {
                ch.tileCol = next.col;
                ch.tileRow = next.row;
                ch.x = toX;
                ch.y = toY;
                ch.pathIdx++;
                ch.moveProgress = 0;
            }
            break;
        }

        case CharState::ACTIVITY: {
            // If agent became active, cancel activity immediately
            if (ch.isActive) {
                ch.state = CharState::IDLE;
                ch.idleActivity = IdleActivity::NONE;
                ch.activityTimer = 0;
                ch.frame = 0;
                ch.frameTimer = 0;
                break;
            }

            // Animate reading activity (2-frame cycle)
            if (ch.idleActivity == IdleActivity::READING) {
                if (ch.frameTimer >= READ_ACTIVITY_FRAME_SEC) {
                    ch.frameTimer -= READ_ACTIVITY_FRAME_SEC;
                    ch.frame = (ch.frame + 1) % 2;
                }
            }
            // COFFEE/WATER/SOCIALIZING: standing frame, no animation

            // Count down activity duration
            ch.activityTimer -= dt;
            if (ch.activityTimer <= 0) {
                ch.state = CharState::IDLE;
                ch.idleActivity = IdleActivity::NONE;
                ch.activityTimer = 0;
                ch.activityCooldown = true;
                ch.frame = 0;
                ch.frameTimer = 0;
                ch.wanderTimer = randomRange(ACTIVITY_COOLDOWN_SEC, ACTIVITY_COOLDOWN_SEC + WANDER_PAUSE_MIN_SEC);
                walkToZone(ch);
            }
            break;
        }

        default:
            break;
    }

    // Tick bubble timer
    if (ch.bubbleType > 0 && ch.bubbleTimer > 0) {
        ch.bubbleTimer -= dt;
        if (ch.bubbleTimer <= 0) {
            ch.bubbleType = 0;
            ch.bubbleTimer = 0;
        }
    }
}

void OfficeState::startWalk(Character& ch, int8_t goalCol, int8_t goalRow) {
    PathNode pathBuf[64];
    uint8_t pathLen = 0;
    if (findPath(ch.tileCol, ch.tileRow, goalCol, goalRow, pathBuf, pathLen)) {
        memcpy(ch.path, pathBuf, pathLen * sizeof(PathNode));
        ch.pathLen = pathLen;
        ch.pathIdx = 0;
        ch.moveProgress = 0;
        ch.state = CharState::WALK;
        ch.frame = 0;
        ch.frameTimer = 0;
    }
}

void OfficeState::startWander(Character& ch) {
    // Pick a random walkable tile anywhere
    for (int attempt = 0; attempt < 20; attempt++) {
        int8_t col = (int8_t)randomInt(1, GRID_COLS - 2);
        int8_t row = (int8_t)randomInt(1, GRID_ROWS - 1);
        if (isWalkable(col, row)) {
            startWalk(ch, col, row);
            ch.wanderCount++;
            return;
        }
    }
}

void OfficeState::startZoneWander(Character& ch) {
    int colMin, colMax, rowMin, rowMax;
    if (ch.homeZone == SocialZone::BREAK_ROOM) {
        colMin = ZONE_BREAK_COL_MIN; colMax = ZONE_BREAK_COL_MAX;
        rowMin = ZONE_BREAK_ROW_MIN; rowMax = ZONE_BREAK_ROW_MAX;
    } else {
        colMin = ZONE_LIB_COL_MIN; colMax = ZONE_LIB_COL_MAX;
        rowMin = ZONE_LIB_ROW_MIN; rowMax = ZONE_LIB_ROW_MAX;
    }

    for (int attempt = 0; attempt < 30; attempt++) {
        int8_t col = (int8_t)randomInt(colMin, colMax);
        int8_t row = (int8_t)randomInt(rowMin, rowMax);
        if (isWalkable(col, row)) {
            startWalk(ch, col, row);
            ch.wanderCount++;
            return;
        }
    }
}

void OfficeState::walkToZone(Character& ch) {
    ch.idleActivity = IdleActivity::NONE;
    int colMin, colMax, rowMin, rowMax;
    if (ch.homeZone == SocialZone::BREAK_ROOM) {
        colMin = ZONE_BREAK_COL_MIN; colMax = ZONE_BREAK_COL_MAX;
        rowMin = ZONE_BREAK_ROW_MIN; rowMax = ZONE_BREAK_ROW_MAX;
    } else {
        colMin = ZONE_LIB_COL_MIN; colMax = ZONE_LIB_COL_MAX;
        rowMin = ZONE_LIB_ROW_MIN; rowMax = ZONE_LIB_ROW_MAX;
    }

    // Try random tiles in zone
    for (int attempt = 0; attempt < 30; attempt++) {
        int8_t col = (int8_t)randomInt(colMin, colMax);
        int8_t row = (int8_t)randomInt(rowMin, rowMax);
        if (isWalkable(col, row)) {
            startWalk(ch, col, row);
            return;
        }
    }

    // Fallback: scan zone for any walkable tile
    for (int r = rowMin; r <= rowMax; r++) {
        for (int c = colMin; c <= colMax; c++) {
            if (isWalkable((int8_t)c, (int8_t)r)) {
                startWalk(ch, (int8_t)c, (int8_t)r);
                return;
            }
        }
    }

    // If no walkable tile in zone, just go idle where we are
    ch.state = CharState::IDLE;
    ch.frame = 0;
    ch.frameTimer = 0;
    ch.wanderTimer = randomRange(WANDER_PAUSE_MIN_SEC, WANDER_PAUSE_MAX_SEC);
}

void OfficeState::snapToSeat(Character& ch) {
    if (ch.seatIdx < 0) return;
    const auto& ws = WORKSTATIONS[ch.seatIdx];
    ch.tileCol = (int8_t)ws.seatCol;
    ch.tileRow = (int8_t)ws.seatRow;
    ch.x = ws.seatCol * TILE_SIZE + TILE_SIZE / 2.0f;
    ch.y = ws.seatRow * TILE_SIZE + TILE_SIZE / 2.0f;
    ch.dir = ws.facingDir;
}

// ── Idle Activity Logic ──────────────────────────────────

void OfficeState::startIdleActivity(Character& ch) {
    // Roll random activity: READING 30%, COFFEE 20%, WATER 20%, SOCIALIZING 30%
    float roll = randomRange(0, 1.0f);
    IdleActivity activity;
    if (roll < 0.30f) {
        activity = IdleActivity::READING;
    } else if (roll < 0.50f) {
        activity = IdleActivity::COFFEE;
    } else if (roll < 0.70f) {
        activity = IdleActivity::WATER;
    } else {
        activity = IdleActivity::SOCIALIZING;
    }
    pickActivityTarget(ch, activity);
}

void OfficeState::pickActivityTarget(Character& ch, IdleActivity activity) {
    int charIdx = -1;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (&_chars[i] == &ch) { charIdx = i; break; }
    }

    if (activity == IdleActivity::SOCIALIZING) {
        // Find another idle/unassigned character to socialize with
        int target = findSocializeTarget(charIdx);
        if (target < 0) {
            // No target available, fall back to zone wander
            startZoneWander(ch);
            return;
        }
        // Walk to a tile adjacent to the target
        const Character& other = _chars[target];
        // Try tiles around the target's current position
        static const int8_t DX[] = {0, 0, 1, -1};
        static const int8_t DY[] = {1, -1, 0, 0};
        for (int attempt = 0; attempt < 8; attempt++) {
            int d = randomInt(0, 3);
            int8_t col = other.tileCol + DX[d];
            int8_t row = other.tileRow + DY[d];
            if (isWalkable(col, row) && isInteractionPointFree(col, row, charIdx)) {
                ch.idleActivity = IdleActivity::SOCIALIZING;
                // Compute facing direction toward target (stored for restore after walk)
                int dc = other.tileCol - col;
                int dr = other.tileRow - row;
                if (dc > 0) ch.activityDir = Dir::RIGHT;
                else if (dc < 0) ch.activityDir = Dir::LEFT;
                else if (dr > 0) ch.activityDir = Dir::DOWN;
                else ch.activityDir = Dir::UP;
                startWalk(ch, col, row);
                if (ch.state != CharState::WALK) {
                    ch.idleActivity = IdleActivity::NONE;
                }
                return;
            }
        }
        // Couldn't find adjacent tile, fall back
        startZoneWander(ch);
        return;
    }

    // Furniture-based activities: READING, COFFEE, WATER
    const InteractionPoint* points;
    int numPoints;
    switch (activity) {
        case IdleActivity::READING:
            points = READING_POINTS;
            numPoints = NUM_READING_POINTS;
            break;
        case IdleActivity::COFFEE:
            points = COFFEE_POINTS;
            numPoints = NUM_COFFEE_POINTS;
            break;
        case IdleActivity::WATER:
            points = WATER_POINTS;
            numPoints = NUM_WATER_POINTS;
            break;
        default:
            startZoneWander(ch);
            return;
    }

    // Try random interaction points
    for (int attempt = 0; attempt < numPoints * 2; attempt++) {
        int idx = randomInt(0, numPoints - 1);
        const auto& pt = points[idx];
        if (isWalkable(pt.col, pt.row) && isInteractionPointFree(pt.col, pt.row, charIdx)) {
            ch.idleActivity = activity;
            ch.activityDir = pt.facingDir;
            startWalk(ch, pt.col, pt.row);
            if (ch.state != CharState::WALK) {
                ch.idleActivity = IdleActivity::NONE;
            }
            return;
        }
    }

    // All points occupied, fall back to zone wander
    startZoneWander(ch);
}

bool OfficeState::isInteractionPointFree(int8_t col, int8_t row, int excludeIdx) const {
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (i == excludeIdx) continue;
        if (!_chars[i].alive) continue;
        // Check if standing on this tile
        if (_chars[i].tileCol == col && _chars[i].tileRow == row) return false;
        // Check if walking to this tile (last node in path)
        if (_chars[i].state == CharState::WALK && _chars[i].pathLen > 0) {
            const PathNode& dest = _chars[i].path[_chars[i].pathLen - 1];
            if (dest.col == col && dest.row == row) return false;
        }
    }
    return true;
}

int OfficeState::findSocializeTarget(int charIdx) {
    int candidates[MAX_AGENTS];
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (i == charIdx) continue;
        if (!_chars[i].alive) continue;
        if (_chars[i].agentId >= 0) continue;  // skip assigned chars
        if (_chars[i].state == CharState::IDLE || _chars[i].state == CharState::ACTIVITY) {
            candidates[count++] = i;
        }
    }
    if (count == 0) return -1;
    return candidates[randomInt(0, count - 1)];
}

bool OfficeState::isWalkable(int8_t col, int8_t row) const {
    if (col < 0 || col >= GRID_COLS || row < 0 || row >= GRID_ROWS) return false;
    return _tiles[row][col] == TileType::FLOOR;
}

// BFS pathfinding
bool OfficeState::findPath(int8_t fromCol, int8_t fromRow, int8_t toCol, int8_t toRow,
                           PathNode* outPath, uint8_t& outLen) {
    if (fromCol == toCol && fromRow == toRow) {
        outLen = 0;
        return true;
    }

    // BFS with parent tracking
    static const int8_t DX[] = {0, 0, 1, -1};
    static const int8_t DY[] = {1, -1, 0, 0};

    bool visited[GRID_ROWS][GRID_COLS];
    int8_t parentCol[GRID_ROWS][GRID_COLS];
    int8_t parentRow[GRID_ROWS][GRID_COLS];
    memset(visited, 0, sizeof(visited));
    memset(parentCol, -1, sizeof(parentCol));
    memset(parentRow, -1, sizeof(parentRow));

    // BFS queue (fixed size)
    struct QNode { int8_t col, row; };
    QNode queue[GRID_ROWS * GRID_COLS];
    int qHead = 0, qTail = 0;

    visited[fromRow][fromCol] = true;
    queue[qTail++] = {fromCol, fromRow};

    bool found = false;
    while (qHead < qTail) {
        QNode cur = queue[qHead++];

        if (cur.col == toCol && cur.row == toRow) {
            found = true;
            break;
        }

        for (int d = 0; d < 4; d++) {
            int8_t nc = cur.col + DX[d];
            int8_t nr = cur.row + DY[d];
            if (nc < 0 || nc >= GRID_COLS || nr < 0 || nr >= GRID_ROWS) continue;
            if (visited[nr][nc]) continue;
            // Allow walking to destination even if it's "blocked" (e.g., seat tile)
            if (!isWalkable(nc, nr) && !(nc == toCol && nr == toRow)) continue;
            if (qTail >= GRID_ROWS * GRID_COLS) break;
            visited[nr][nc] = true;
            parentCol[nr][nc] = cur.col;
            parentRow[nr][nc] = cur.row;
            queue[qTail++] = {nc, nr};
        }
    }

    if (!found) {
        outLen = 0;
        return false;
    }

    // Reconstruct path (reverse)
    PathNode revPath[64];
    int len = 0;
    int8_t cc = toCol, cr = toRow;
    while (cc != fromCol || cr != fromRow) {
        if (len >= 64) { outLen = 0; return false; }
        revPath[len++] = {cc, cr};
        int8_t pc = parentCol[cr][cc];
        int8_t pr = parentRow[cr][cc];
        cc = pc;
        cr = pr;
    }

    // Reverse into output
    outLen = (uint8_t)len;
    for (int i = 0; i < len; i++) {
        outPath[i] = revPath[len - 1 - i];
    }
    return true;
}

float OfficeState::randomRange(float minVal, float maxVal) {
    return minVal + ((float)random(10000) / 10000.0f) * (maxVal - minVal);
}

int OfficeState::randomInt(int minVal, int maxVal) {
    return minVal + random(maxVal - minVal + 1);
}

// ── Pet (French Bulldog) ─────────────────────────────────

void OfficeState::initPet() {
    memset(&_pet, 0, sizeof(Pet));
    _pet.dir = Dir::RIGHT;
    _pet.behavior = DogBehavior::WANDER;
    _pet.phaseTimer = DOG_WANDER_DURATION_SEC;
    _pet.napTimer = DOG_NAP_INTERVAL_SEC;
    _pet.targetPickTimer = DOG_PICK_TARGET_SEC;
    _pet.followTarget = -1;
    _pet.pendingSound = SoundId::COUNT;
    _pet.lastTargetCol = -1;
    _pet.lastTargetRow = -1;
    _pet.wanderTimer = randomRange(DOG_WANDER_PAUSE_MIN_SEC, DOG_WANDER_PAUSE_MAX_SEC);

    // Place at a random walkable tile
    for (int attempt = 0; attempt < 40; attempt++) {
        int8_t col = (int8_t)randomInt(2, GRID_COLS - 2);
        int8_t row = (int8_t)randomInt(2, GRID_ROWS - 2);
        if (isWalkable(col, row)) {
            _pet.tileCol = col;
            _pet.tileRow = row;
            _pet.x = col * TILE_SIZE + TILE_SIZE / 2.0f;
            _pet.y = row * TILE_SIZE + TILE_SIZE / 2.0f;
            return;
        }
    }
    // Fallback
    _pet.tileCol = 5;
    _pet.tileRow = 3;
    _pet.x = 5 * TILE_SIZE + TILE_SIZE / 2.0f;
    _pet.y = 3 * TILE_SIZE + TILE_SIZE / 2.0f;
}

void OfficeState::petStartWalk(int8_t goalCol, int8_t goalRow) {
    PathNode pathBuf[64];
    uint8_t pathLen = 0;
    if (findPath(_pet.tileCol, _pet.tileRow, goalCol, goalRow, pathBuf, pathLen)) {
        memcpy(_pet.path, pathBuf, pathLen * sizeof(PathNode));
        _pet.pathLen = pathLen;
        _pet.pathIdx = 0;
        _pet.moveProgress = 0;
        _pet.walking = true;
        _pet.isRunning = false;
        _pet.frame = 0;
        _pet.frameTimer = 0;
    }
}

void OfficeState::petWander() {
    for (int attempt = 0; attempt < 20; attempt++) {
        int8_t col = (int8_t)randomInt(1, GRID_COLS - 2);
        int8_t row = (int8_t)randomInt(1, GRID_ROWS - 1);
        if (isWalkable(col, row)) {
            petStartWalk(col, row);
            return;
        }
    }
}

void OfficeState::petPickTarget() {
    // Pick a random alive character
    int8_t prevTarget = _pet.followTarget;
    int candidates[MAX_AGENTS];
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (_chars[i].alive) candidates[count++] = i;
    }
    if (count > 0) {
        int8_t nextTarget = (int8_t)candidates[randomInt(0, count - 1)];
        if (nextTarget != prevTarget) {
            _pet.followTarget = nextTarget;
            _pet.lastTargetCol = -1;
            _pet.lastTargetRow = -1;
            queueSound(SoundId::DOG_BARK);
        }
    }
}

void OfficeState::petFollowNear() {
    if (_pet.followTarget < 0 || _pet.followTarget >= MAX_AGENTS) return;
    const Character& target = _chars[_pet.followTarget];
    if (!target.alive) {
        petPickTarget();
        return;
    }

    int8_t tCol = target.tileCol;
    int8_t tRow = target.tileRow;

    // Hysteresis: only re-pathfind if target moved significantly
    if (_pet.lastTargetCol >= 0) {
        int dx = abs(tCol - _pet.lastTargetCol);
        int dy = abs(tRow - _pet.lastTargetRow);
        if (dx + dy <= DOG_FOLLOW_HYSTERESIS) return;
    }

    // Already close enough?
    int distX = abs(_pet.tileCol - tCol);
    int distY = abs(_pet.tileRow - tRow);
    if (distX + distY <= 2) return;

    // Pick a walkable tile within DOG_FOLLOW_RADIUS of target
    for (int attempt = 0; attempt < 30; attempt++) {
        int8_t col = (int8_t)(tCol + randomInt(-DOG_FOLLOW_RADIUS, DOG_FOLLOW_RADIUS));
        int8_t row = (int8_t)(tRow + randomInt(-DOG_FOLLOW_RADIUS, DOG_FOLLOW_RADIUS));
        if (col < 0 || col >= GRID_COLS || row < 0 || row >= GRID_ROWS) continue;
        int d = abs(col - tCol) + abs(row - tRow);
        if (d < 2 || d > DOG_FOLLOW_RADIUS) continue;
        if (isWalkable(col, row)) {
            petStartWalk(col, row);
            _pet.lastTargetCol = tCol;
            _pet.lastTargetRow = tRow;
            return;
        }
    }
}

void OfficeState::updatePet(float dt) {
    _pet.frameTimer += dt;

    // ── Nap timer (always counts down) ──
    _pet.napTimer -= dt;
    if (_pet.behavior != DogBehavior::NAP && _pet.napTimer <= 0) {
        _pet.behavior = DogBehavior::NAP;
        _pet.napRemaining = DOG_NAP_DURATION_SEC;
        _pet.walking = false;
        _pet.isRunning = false;
        _pet.pathLen = 0;
        _pet.frame = 0;
        _pet.frameTimer = 0;
        _pet.isSitting = false;
        _pet.isPeeing = false;
    }

    // ── Idle animations (cycle 8 idle frames) ──
    if (!_pet.walking && !_pet.isPeeing && _pet.behavior != DogBehavior::NAP) {
        _pet.idleFrameTimer += dt;
        if (_pet.idleFrameTimer >= DOG_IDLE_FRAME_SEC) {
            _pet.idleFrameTimer -= DOG_IDLE_FRAME_SEC;
            _pet.idleFrame = (_pet.idleFrame + 1) % DOG_IDLE_COUNT;
        }
    }

    // ── Pee timer tick ──
    if (_pet.isPeeing) {
        _pet.peeTimer -= dt;
        if (_pet.peeTimer <= 0) _pet.isPeeing = false;
    }

    // ── Behavior FSM ──
    switch (_pet.behavior) {
        case DogBehavior::NAP: {
            _pet.napRemaining -= dt;
            if (_pet.napRemaining <= 0) {
                _pet.behavior = DogBehavior::WANDER;
                _pet.phaseTimer = DOG_WANDER_DURATION_SEC;
                _pet.napTimer = DOG_NAP_INTERVAL_SEC;
                _pet.wanderTimer = randomRange(DOG_WANDER_PAUSE_MIN_SEC, DOG_WANDER_PAUSE_MAX_SEC);
            }
            break;
        }

        case DogBehavior::FOLLOW: {
            _pet.phaseTimer -= dt;
            _pet.targetPickTimer -= dt;

            if (_pet.phaseTimer <= 0) {
                _pet.behavior = DogBehavior::WANDER;
                _pet.phaseTimer = DOG_WANDER_DURATION_SEC;
                _pet.followTarget = -1;
                _pet.isSitting = false;
                _pet.wanderTimer = randomRange(DOG_WANDER_PAUSE_MIN_SEC, DOG_WANDER_PAUSE_MAX_SEC);
                break;
            }

            if (_pet.targetPickTimer <= 0) {
                petPickTarget();
                _pet.targetPickTimer = DOG_PICK_TARGET_SEC;
            }

            // Check if follow target is seated -- dog sits nearby
            _pet.isSitting = false;
            if (_pet.followTarget >= 0 && _pet.followTarget < MAX_AGENTS && !_pet.walking) {
                const Character& target = _chars[_pet.followTarget];
                if (target.alive &&
                    (target.state == CharState::TYPE || target.state == CharState::READ)) {
                    int dx = abs(_pet.tileCol - target.tileCol);
                    int dy = abs(_pet.tileRow - target.tileRow);
                    if (dx + dy <= 2) {
                        _pet.isSitting = true;
                    }
                }
            }

            // Re-pathfind periodically while following (not while sitting)
            if (!_pet.walking && !_pet.isSitting) {
                _pet.repathTimer -= dt;
                if (_pet.repathTimer <= 0) {
                    petFollowNear();
                    _pet.repathTimer = DOG_FOLLOW_REPATHFIND_SEC;
                }
            }
            break;
        }

        case DogBehavior::WANDER: {
            _pet.phaseTimer -= dt;
            _pet.targetPickTimer -= dt;

            if (_pet.phaseTimer <= 0) {
                _pet.behavior = DogBehavior::FOLLOW;
                _pet.phaseTimer = DOG_FOLLOW_DURATION_SEC;
                _pet.isPeeing = false;
                if (_pet.followTarget < 0) petPickTarget();
                _pet.repathTimer = 0;
                break;
            }

            if (_pet.targetPickTimer <= 0) {
                petPickTarget();
                _pet.targetPickTimer = DOG_PICK_TARGET_SEC;
            }

            if (!_pet.walking && !_pet.isPeeing) {
                _pet.wanderTimer -= dt;
                if (_pet.wanderTimer <= 0) {
                    // Random chance to pee when pausing
                    if (randomRange(0, 1.0f) < DOG_PEE_CHANCE) {
                        _pet.isPeeing = true;
                        _pet.peeTimer = DOG_PEE_DURATION_SEC;
                        _pet.wanderTimer = DOG_PEE_DURATION_SEC + 0.5f;
                    } else {
                        // Random chance this walk becomes a run
                        bool run = randomRange(0, 1.0f) < DOG_RUN_CHANCE;
                        petWander();
                        if (run && _pet.walking) {
                            _pet.isRunning = true;
                        }
                        _pet.wanderTimer = randomRange(DOG_WANDER_MOVE_MIN_SEC, DOG_WANDER_MOVE_MAX_SEC);
                    }
                }
            }
            break;
        }
    }

    // ── Walk/run movement ──
    if (_pet.walking && _pet.pathIdx < _pet.pathLen) {
        float frameDur = _pet.isRunning ? DOG_RUN_FRAME_DURATION_SEC : DOG_WALK_FRAME_DURATION_SEC;
        int frameCount = _pet.isRunning ? DOG_RUN_COUNT : DOG_WALK_COUNT;
        if (_pet.frameTimer >= frameDur) {
            _pet.frameTimer -= frameDur;
            _pet.frame = (_pet.frame + 1) % frameCount;
        }

        PathNode next = _pet.path[_pet.pathIdx];

        int dc = next.col - _pet.tileCol;
        int dr = next.row - _pet.tileRow;
        if (dc > 0) _pet.dir = Dir::RIGHT;
        else if (dc < 0) _pet.dir = Dir::LEFT;
        else if (dr > 0) _pet.dir = Dir::DOWN;
        else _pet.dir = Dir::UP;

        float speed = _pet.isRunning ? DOG_RUN_SPEED_PX_PER_SEC : DOG_WALK_SPEED_PX_PER_SEC;
        _pet.moveProgress += (speed / TILE_SIZE) * dt;

        float fromX = _pet.tileCol * TILE_SIZE + TILE_SIZE / 2.0f;
        float fromY = _pet.tileRow * TILE_SIZE + TILE_SIZE / 2.0f;
        float toX = next.col * TILE_SIZE + TILE_SIZE / 2.0f;
        float toY = next.row * TILE_SIZE + TILE_SIZE / 2.0f;

        float t = _pet.moveProgress;
        if (t > 1.0f) t = 1.0f;
        _pet.x = fromX + (toX - fromX) * t;
        _pet.y = fromY + (toY - fromY) * t;

        if (_pet.moveProgress >= 1.0f) {
            _pet.tileCol = next.col;
            _pet.tileRow = next.row;
            _pet.x = toX;
            _pet.y = toY;
            _pet.pathIdx++;
            _pet.moveProgress = 0;
        }
    } else if (_pet.walking) {
        _pet.walking = false;
        _pet.isRunning = false;
        _pet.frame = 0;
        _pet.frameTimer = 0;
        _pet.x = _pet.tileCol * TILE_SIZE + TILE_SIZE / 2.0f;
        _pet.y = _pet.tileRow * TILE_SIZE + TILE_SIZE / 2.0f;
    }
}

void OfficeState::setUsageStats(uint8_t curPct, uint8_t wkPct, uint16_t curResetMin, uint16_t wkResetMin) {
    _usage.currentPct = curPct > 100 ? 100 : curPct;
    _usage.weeklyPct = wkPct > 100 ? 100 : wkPct;
    _usage.currentResetMin = curResetMin;
    _usage.weeklyResetMin = wkResetMin;
    _usage.valid = true;
}

// ── Settings Persistence (NVS) ───────────────────────────

void OfficeState::loadSettings() {
    Preferences prefs;
    if (!prefs.begin("pixelagent", true)) {
        _dogSettings.enabled = true;
        _dogSettings.color = DOG_DEFAULT_COLOR;
        _screenFlipped = false;
        return;
    }
    _dogSettings.enabled = prefs.getBool("dogOn", true);
    uint8_t colorVal = prefs.getUChar("dogColor", static_cast<uint8_t>(DOG_DEFAULT_COLOR));
    if (colorVal < DOG_COLOR_COUNT) {
        _dogSettings.color = static_cast<DogColor>(colorVal);
    } else {
        _dogSettings.color = DOG_DEFAULT_COLOR;
    }
    _screenFlipped = prefs.getBool("flipScr", false);
#if defined(HAS_SOUND)
#if defined(BOARD_CYD)
    _soundEnabled = prefs.getBool("soundOn", false);
#else
    _soundEnabled = prefs.getBool("soundOn", true);
#endif
#endif
    prefs.end();
}

void OfficeState::saveSettings() {
    Preferences prefs;
    prefs.begin("pixelagent", false);  // read-write
    prefs.putBool("dogOn", _dogSettings.enabled);
    prefs.putUChar("dogColor", static_cast<uint8_t>(_dogSettings.color));
    prefs.putBool("flipScr", _screenFlipped);
#if defined(HAS_SOUND)
    prefs.putBool("soundOn", _soundEnabled);
#endif
    prefs.end();
}

void OfficeState::setDogEnabled(bool enabled) {
    if (_dogSettings.enabled == enabled) return;
    _dogSettings.enabled = enabled;
    saveSettings();
    if (enabled) {
        initPet();
    } else {
        _pet.pendingSound = SoundId::COUNT;  // clear any queued sound
    }
}

void OfficeState::setScreenFlipped(bool flipped) {
    if (_screenFlipped == flipped) return;
    _screenFlipped = flipped;
    saveSettings();
}

void OfficeState::setDogColor(DogColor color) {
    if (static_cast<uint8_t>(color) >= DOG_COLOR_COUNT) return;
    if (_dogSettings.color == color) return;
    _dogSettings.color = color;
    saveSettings();
}

SoundId OfficeState::consumePendingSound() {
    SoundId id = _pet.pendingSound;
    _pet.pendingSound = SoundId::COUNT;
    return id;
}

void OfficeState::queueSound(SoundId id) {
#if defined(HAS_SOUND)
    if (!_soundEnabled) return;
#endif
    _pet.pendingSound = id;
}

#if defined(HAS_SOUND)
void OfficeState::setSoundEnabled(bool enabled) {
    if (_soundEnabled == enabled) return;
    _soundEnabled = enabled;
    saveSettings();
}
#endif

bool OfficeState::hitTestHamburger(int screenX, int screenY) const {
#if defined(HAS_TOUCH)
    int statusTop = SCREEN_H - STATUS_BAR_H;
    int hx = SCREEN_W - HAMBURGER_W - HAMBURGER_MARGIN;
    int hy = statusTop;
    return screenX >= hx - 4 && screenX <= SCREEN_W &&
           screenY >= hy && screenY <= SCREEN_H;
#else
    (void)screenX; (void)screenY;
    return false;
#endif
}

int OfficeState::hitTestMenuItem(int screenX, int screenY) const {
#if defined(HAS_TOUCH)
    if (!_menuOpen) return -1;

    // Menu positioned: right-aligned above status bar
    int menuX = SCREEN_W - MENU_W - 4;
    int menuY = SCREEN_H - STATUS_BAR_H - MENU_H - 2;

    // Check if tap is within menu bounds
    if (screenX < menuX || screenX >= menuX + MENU_W ||
        screenY < menuY || screenY >= menuY + MENU_H) {
        return -1;
    }

    int relY = screenY - menuY;

    // Row 0: title "Settings" (no-op, but inside menu — don't close)
    if (relY < MENU_ITEM_H) return -2;

    // Row 1: dog toggle — next MENU_ITEM_H pixels
    if (relY < MENU_ITEM_H * 2) return 0;

    // Row 2: color swatches (4 swatches, only active when dog enabled)
    if (relY < MENU_ITEM_H * 3) {
        if (!_dogSettings.enabled) return -2;
        int relX = screenX - menuX;
        for (int i = 0; i < DOG_COLOR_COUNT; i++) {
            int sx = SWATCH_AREA_X + i * (SWATCH_W + SWATCH_GAP);
            if (relX >= sx && relX < sx + SWATCH_W) {
                return 1 + i;  // 1=BLACK, 2=BROWN, 3=GRAY, 4=TAN
            }
        }
        return -2;  // between swatches — inside menu, no action
    }

    // Row 3: flip screen toggle
    if (relY < MENU_ITEM_H * 4) return 5;

#if defined(HAS_SOUND)
    // Row 4: sound toggle
    if (relY < MENU_ITEM_H * 5) return 6;
#endif

    // Bottom padding area — inside menu, no action
    return -2;
#else
    (void)screenX; (void)screenY;
    return -1;
#endif
}
