#include "renderer.h"
#include "splash.h"
#include <string.h>
#include "sprites/characters.h"
#if defined(HAS_BATTERY)
#include "battery.h"
#endif
// WHY: tiles.h is generated by the layout editor and may include furniture sprites.
// When it does (HAS_TILESET_FURNITURE), skip furniture.h to avoid duplicate definitions.
#if __has_include("sprites/tiles.h")
#include "sprites/tiles.h"
#endif
#ifndef HAS_TILESET_FURNITURE
#include "sprites/furniture.h"
#endif
#include "sprites/bubbles.h"
#include "sprites/dog.h"

static_assert(DOG_WALK_BASE + DOG_WALK_COUNT <= DOG_FRAME_COUNT, "Dog walk indices exceed DOG_FRAME_COUNT");
static_assert(DOG_RUN_BASE + DOG_RUN_COUNT <= DOG_FRAME_COUNT, "Dog run indices exceed DOG_FRAME_COUNT");
static_assert(DOG_IDLE_BASE + DOG_IDLE_COUNT <= DOG_FRAME_COUNT, "Dog idle indices exceed DOG_FRAME_COUNT");

// ── Drawing wrappers (apply _yOffset, dispatch to canvas or TFT) ──

inline void Renderer::gfxFillRect(int32_t x, int32_t y, int32_t w, int32_t h, uint32_t c) {
    int32_t ay = y + _yOffset;
    if (_canvas) _canvas->fillRect(x, ay, w, h, c);
    else _tft->fillRect(x, ay, w, h, c);
}

inline void Renderer::gfxDrawPixel(int32_t x, int32_t y, uint32_t c) {
    int32_t ay = y + _yOffset;
    if (_canvas) _canvas->drawPixel(x, ay, c);
    else _tft->drawPixel(x, ay, c);
}

inline void Renderer::gfxFillCircle(int32_t cx, int32_t cy, int32_t r, uint32_t c) {
    int32_t ay = cy + _yOffset;
    if (_canvas) _canvas->fillCircle(cx, ay, r, c);
    else _tft->fillCircle(cx, ay, r, c);
}

inline void Renderer::gfxSetTextColor(uint32_t c) {
    if (_canvas) _canvas->setTextColor(c);
    else _tft->setTextColor(c);
}

inline void Renderer::gfxSetTextSize(uint8_t s) {
    if (_canvas) _canvas->setTextSize(s);
    else _tft->setTextSize(s);
}

inline void Renderer::gfxDrawString(const char* str, int32_t x, int32_t y) {
    int32_t ay = y + _yOffset;
    if (_canvas) _canvas->drawString(str, x, ay);
    else _tft->drawString(str, x, ay);
}

// ── Transport & Battery Icon Bitmaps (5x8, 1 byte/row, MSB-first) ──

// USB icon: connector shape
static const uint8_t ICON_USB[] PROGMEM  = { 0x20,0x70,0x20,0xA8,0xA8,0x70,0x20,0x70 };
// Bluetooth rune
static const uint8_t ICON_BT[] PROGMEM   = { 0x20,0x30,0xA8,0x70,0x70,0xA8,0x30,0x20 };
#if defined(HAS_BATTERY)
// Lightning bolt
static const uint8_t ICON_BOLT[] PROGMEM = { 0x30,0x20,0x60,0xF0,0x30,0x20,0x40,0x00 };
#endif

void Renderer::gfxDrawMonoBitmap(int32_t x, int32_t y, const uint8_t* bitmap,
                                 int32_t w, int32_t h, uint32_t color) {
    for (int32_t row = 0; row < h; row++) {
        uint8_t bits = pgm_read_byte(&bitmap[row]);
        for (int32_t col = 0; col < w; col++) {
            // MSB-first: bit 7 is leftmost pixel of the 8-bit byte
            // For a 5px wide icon, only bits 7..3 are used
            if (bits & (0x80 >> col)) {
                gfxDrawPixel(x + col, y + row, color);
            }
        }
    }
}

// ── Initialization ────────────────────────────────────────

void Renderer::begin(TFT_eSPI& tft) {
    _tft = &tft;
    _canvas = new TFT_eSprite(&tft);

    // Try full-screen sprite (works with PSRAM)
    void* buf = _canvas->createSprite(SCREEN_W, SCREEN_H);
    if (buf) {
        _frameBuffer = (uint16_t*)buf;  // save for screenshot access
        _canvas->setSwapBytes(true);
        _clipYMin = 0;
        _clipYMax = SCREEN_H;
        Serial.println("[renderer] full-screen buffer OK");
        return;
    }

    // Try strip buffer (fits in ESP32 DRAM without PSRAM)
    _stripHeight = STRIP_HEIGHT;
    buf = _canvas->createSprite(SCREEN_W, _stripHeight);
    if (buf) {
        _canvas->setSwapBytes(true);
        _stripMode = true;
        _stripCount = (SCREEN_H + _stripHeight - 1) / _stripHeight;
        _clipYMin = 0;
        _clipYMax = SCREEN_H;
        Serial.printf("[renderer] strip-buffer mode (%dx%d, %d strips)\n",
                      SCREEN_W, _stripHeight, _stripCount);
        return;
    }

    // Last resort: direct TFT rendering (will flicker)
    Serial.println("[renderer] no buffer — direct TFT mode");
    delete _canvas;
    _canvas = nullptr;
    _directMode = true;
    _clipYMin = 0;
    _clipYMax = SCREEN_H;
    _tft->setSwapBytes(true);
    _tft->fillScreen(COLOR_BG);
}

// ── Frame rendering ───────────────────────────────────────

void Renderer::renderFrame(OfficeState& office, void (*interStripCb)()) {
    if (!_canvas && !_directMode) return;
    _currentOffice = &office;

    // Track FPS
    uint32_t now = millis();
    if (_lastRenderMs > 0) {
        uint32_t elapsed = now - _lastRenderMs;
        if (elapsed > 0) {
            float instantFps = 1000.0f / elapsed;
            _fps = _fps * 0.9f + instantFps * 0.1f; // smoothed
        }
    }
    _lastRenderMs = now;

    if (_stripMode) {
        for (int s = 0; s < _stripCount; s++) {
            int stripTop = s * _stripHeight;
            int stripBot = stripTop + _stripHeight;
            if (stripBot > SCREEN_H) stripBot = SCREEN_H;

            _clipYMin = stripTop;
            _clipYMax = stripBot;
            _yOffset = -stripTop;

            _canvas->fillSprite(COLOR_BG);
            drawScene(office);
            _canvas->pushSprite(0, stripTop);
            if (interStripCb) interStripCb();
        }
    } else if (_canvas) {
        // Full-screen buffered
        _canvas->fillSprite(COLOR_BG);
        _yOffset = 0;
        drawScene(office);
        _canvas->pushSprite(0, 0);
    } else {
        // Direct mode (flickers but works as last resort)
        _yOffset = 0;
        drawScene(office);
    }
}

void Renderer::drawScene(OfficeState& office) {
    // 1. Draw floor tiles
    drawFloor(office.getTileMap());

    // 2. Fill gap between grid bottom and status bar
    int gridBottom = GRID_ROWS * TILE_SIZE;
    int statusTop = SCREEN_H - STATUS_BAR_H;
    if (gridBottom < statusTop && gridBottom < _clipYMax && statusTop > _clipYMin) {
        gfxFillRect(0, gridBottom, SCREEN_W, statusTop - gridBottom, COLOR_BG);
    }

    // 3. Draw furniture
    drawFurniture();

    // 4. Collect and depth-sort characters + dog
    // Use index -1 to represent the dog in the sort
    Character* chars = office.getCharacters();
    const Pet& pet = office.getPet();
    int indices[MAX_AGENTS + 1]; // +1 for dog
    float sortY[MAX_AGENTS + 1];
    int count = 0;
    for (int i = 0; i < MAX_AGENTS; i++) {
        if (chars[i].alive) {
            indices[count] = i;
            sortY[count] = chars[i].y;
            count++;
        }
    }
    // Add dog as index -1 (only if enabled)
    if (office.getDogSettings().enabled) {
        indices[count] = -1;
        sortY[count] = pet.y;
        count++;
    }

    // Insertion sort by Y
    for (int i = 1; i < count; i++) {
        int keyIdx = indices[i];
        float keyY = sortY[i];
        int j = i - 1;
        while (j >= 0 && sortY[j] > keyY) {
            indices[j + 1] = indices[j];
            sortY[j + 1] = sortY[j];
            j--;
        }
        indices[j + 1] = keyIdx;
        sortY[j + 1] = keyY;
    }

    // 5. Draw characters and dog in depth order
    for (int i = 0; i < count; i++) {
        if (indices[i] == -1) {
            drawDog(pet, office.getDogSettings().color);
        } else {
            const Character& ch = chars[indices[i]];
            if (ch.state == CharState::SPAWN || ch.state == CharState::DESPAWN) {
                drawSpawnEffect(ch);
            } else {
                drawCharacter(ch);
            }
        }
    }

    // 6. Draw speech bubbles (skip dog index -1)
    for (int i = 0; i < count; i++) {
        if (indices[i] < 0) continue;
        const Character& ch = chars[indices[i]];
        if (ch.bubbleType > 0) {
            drawBubble(ch);
        }
    }

    // 7. Draw status bar
    drawStatusBar(office);

#if defined(HAS_TOUCH)
    // 9. Draw menu overlay (on top of everything)
    if (office.isMenuOpen()) {
        drawMenuOverlay(office);
    }
#endif
}

void Renderer::drawFloor(const TileType* tiles) {
    for (int r = 0; r < GRID_ROWS; r++) {
        int tileTop = r * TILE_SIZE;
        if (tileTop + TILE_SIZE <= _clipYMin || tileTop >= _clipYMax) continue;
        for (int c = 0; c < GRID_COLS; c++) {
            int x = c * TILE_SIZE;
            int y = tileTop;
#if defined(HAS_TILESET_TILES)
            drawRGB565Sprite(x, y, TILE_MAP[r][c], TILE_SIZE, TILE_SIZE);
#else
            if (tiles[r * GRID_COLS + c] == TileType::WALL) {
                gfxFillRect(x, y, TILE_SIZE, TILE_SIZE, COLOR_WALL);
            } else {
                uint16_t floorColor = ((r + c) % 2 == 0) ? COLOR_FLOOR_ALT : COLOR_FLOOR;
                gfxFillRect(x, y, TILE_SIZE, TILE_SIZE, floorColor);
            }
#endif
        }
    }
}

// Generated by tools/layout_editor.html
void Renderer::drawFurniture() {
    drawRGB565Sprite(1 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_DESK_D, SPRITE_DESK_D_W, SPRITE_DESK_D_H);
    drawRGB565Sprite(6 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_DESK_D, SPRITE_DESK_D_W, SPRITE_DESK_D_H);
    drawRGB565Sprite(1 * TILE_SIZE, 7 * TILE_SIZE, SPRITE_DESK_D, SPRITE_DESK_D_W, SPRITE_DESK_D_H);
    drawRGB565Sprite(6 * TILE_SIZE, 7 * TILE_SIZE, SPRITE_DESK_D, SPRITE_DESK_D_W, SPRITE_DESK_D_H);
    drawRGB565Sprite(3 * TILE_SIZE, 4 * TILE_SIZE, SPRITE_DESK_VERT, SPRITE_DESK_VERT_W, SPRITE_DESK_VERT_H);
    drawRGB565Sprite(6 * TILE_SIZE, 4 * TILE_SIZE, SPRITE_DESK_VERT, SPRITE_DESK_VERT_W, SPRITE_DESK_VERT_H);
    drawRGB565Sprite(2 * TILE_SIZE, 11 * TILE_SIZE, SPRITE_CHAIR_A, SPRITE_CHAIR_A_W, SPRITE_CHAIR_A_H);
    drawRGB565Sprite(7 * TILE_SIZE, 11 * TILE_SIZE, SPRITE_CHAIR_A, SPRITE_CHAIR_A_W, SPRITE_CHAIR_A_H);
    drawRGB565Sprite(2 * TILE_SIZE, 8 * TILE_SIZE, SPRITE_CHAIR_B, SPRITE_CHAIR_B_W, SPRITE_CHAIR_B_H);
    drawRGB565Sprite(7 * TILE_SIZE, 8 * TILE_SIZE, SPRITE_CHAIR_B, SPRITE_CHAIR_B_W, SPRITE_CHAIR_B_H);
    drawRGB565Sprite(2 * TILE_SIZE, 4 * TILE_SIZE, SPRITE_CHAIR_C, SPRITE_CHAIR_C_W, SPRITE_CHAIR_C_H);
    drawRGB565Sprite(7 * TILE_SIZE, 4 * TILE_SIZE, SPRITE_CHAIR_D, SPRITE_CHAIR_D_W, SPRITE_CHAIR_D_H);
    drawRGB565Sprite(17 * TILE_SIZE, 8 * TILE_SIZE, SPRITE_SEAT_1, SPRITE_SEAT_1_W, SPRITE_SEAT_1_H);
    drawRGB565Sprite(15 * TILE_SIZE, 8 * TILE_SIZE, SPRITE_SEAT_1, SPRITE_SEAT_1_W, SPRITE_SEAT_1_H);
    drawRGB565Sprite(15 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_SEAT_2, SPRITE_SEAT_2_W, SPRITE_SEAT_2_H);
    drawRGB565Sprite(17 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_SEAT_2, SPRITE_SEAT_2_W, SPRITE_SEAT_2_H);
    drawRGB565Sprite(19 * TILE_SIZE, 9 * TILE_SIZE, SPRITE_SEAT_4, SPRITE_SEAT_4_W, SPRITE_SEAT_4_H);
    drawRGB565Sprite(19 * TILE_SIZE, 11 * TILE_SIZE, SPRITE_SEAT_4, SPRITE_SEAT_4_W, SPRITE_SEAT_4_H);
    drawRGB565Sprite(18 * TILE_SIZE, 3 * TILE_SIZE, SPRITE_STOOL, SPRITE_STOOL_W, SPRITE_STOOL_H);

    // Static decorations
    drawRGB565Sprite(12 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_WATER_COOLER, SPRITE_WATER_COOLER_W, SPRITE_WATER_COOLER_H);
    drawRGB565Sprite(16 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_COUNTER_TOP, SPRITE_COUNTER_TOP_W, SPRITE_COUNTER_TOP_H);
    drawRGB565Sprite(14 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_COUNTER_TOP, SPRITE_COUNTER_TOP_W, SPRITE_COUNTER_TOP_H);
    drawRGB565Sprite(14 * TILE_SIZE, 2 * TILE_SIZE, SPRITE_COUNTER_BOTTOM_A, SPRITE_COUNTER_BOTTOM_A_W, SPRITE_COUNTER_BOTTOM_A_H);
    drawRGB565Sprite(16 * TILE_SIZE, 2 * TILE_SIZE, SPRITE_COUNTER_BOTTOM_A, SPRITE_COUNTER_BOTTOM_A_W, SPRITE_COUNTER_BOTTOM_A_H);
    drawRGB565Sprite(18 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_VENDING_MACHINE, SPRITE_VENDING_MACHINE_W, SPRITE_VENDING_MACHINE_H);
    drawRGB565Sprite(9 * TILE_SIZE, 13 * TILE_SIZE, SPRITE_PLANT_BOTTOM_BROWN, SPRITE_PLANT_BOTTOM_BROWN_W, SPRITE_PLANT_BOTTOM_BROWN_H);
    drawRGB565Sprite(0 * TILE_SIZE, 13 * TILE_SIZE, SPRITE_PLANT_BOTTOM_BROWN, SPRITE_PLANT_BOTTOM_BROWN_W, SPRITE_PLANT_BOTTOM_BROWN_H);
    drawRGB565Sprite(0 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_PLANT_TOP_C, SPRITE_PLANT_TOP_C_W, SPRITE_PLANT_TOP_C_H);
    drawRGB565Sprite(9 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_PLANT_TOP_D, SPRITE_PLANT_TOP_D_W, SPRITE_PLANT_TOP_D_H);
    drawRGB565Sprite(12 * TILE_SIZE, 5 * TILE_SIZE, SPRITE_BOOKSHELF_A, SPRITE_BOOKSHELF_A_W, SPRITE_BOOKSHELF_A_H);
    drawRGB565Sprite(16 * TILE_SIZE, 5 * TILE_SIZE, SPRITE_BOOKSHELF_A, SPRITE_BOOKSHELF_A_W, SPRITE_BOOKSHELF_A_H);
    drawRGB565Sprite(14 * TILE_SIZE, 5 * TILE_SIZE, SPRITE_BOOKSHELF_B, SPRITE_BOOKSHELF_B_W, SPRITE_BOOKSHELF_B_H);
    drawRGB565Sprite(18 * TILE_SIZE, 5 * TILE_SIZE, SPRITE_BOOKSHELF_B, SPRITE_BOOKSHELF_B_W, SPRITE_BOOKSHELF_B_H);
    drawRGB565Sprite(19 * TILE_SIZE, 3 * TILE_SIZE, SPRITE_TABLE, SPRITE_TABLE_W, SPRITE_TABLE_H);
    drawRGB565Sprite(16 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_COFFEE_MAKER, SPRITE_COFFEE_MAKER_W, SPRITE_COFFEE_MAKER_H);
    drawRGB565Sprite(17 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_COFFEE_MAKER, SPRITE_COFFEE_MAKER_W, SPRITE_COFFEE_MAKER_H);
    drawRGB565Sprite(13 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_PLANT_TOP_E, SPRITE_PLANT_TOP_E_W, SPRITE_PLANT_TOP_E_H);
    drawRGB565Sprite(13 * TILE_SIZE, 2 * TILE_SIZE, SPRITE_PLANT_BOTTOM_WHITE, SPRITE_PLANT_BOTTOM_WHITE_W, SPRITE_PLANT_BOTTOM_WHITE_H);
    drawRGB565Sprite(11 * TILE_SIZE, 5 * TILE_SIZE, SPRITE_PLANT_TOP_G, SPRITE_PLANT_TOP_G_W, SPRITE_PLANT_TOP_G_H);
    drawRGB565Sprite(11 * TILE_SIZE, 6 * TILE_SIZE, SPRITE_PLANT_BOTTOM_WHITE, SPRITE_PLANT_BOTTOM_WHITE_W, SPRITE_PLANT_BOTTOM_WHITE_H);
    drawRGB565Sprite(18 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_PLANT_TOP_2, SPRITE_PLANT_TOP_2_W, SPRITE_PLANT_TOP_2_H);
    drawRGB565Sprite(18 * TILE_SIZE, 13 * TILE_SIZE, SPRITE_PLANT_BOTTOM_WHITE, SPRITE_PLANT_BOTTOM_WHITE_W, SPRITE_PLANT_BOTTOM_WHITE_H);
    drawRGB565Sprite(14 * TILE_SIZE, 13 * TILE_SIZE, SPRITE_PLANT_BOTTOM_WHITE, SPRITE_PLANT_BOTTOM_WHITE_W, SPRITE_PLANT_BOTTOM_WHITE_H);
    drawRGB565Sprite(14 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_PLANT_TOP_2, SPRITE_PLANT_TOP_2_W, SPRITE_PLANT_TOP_2_H);
    drawRGB565Sprite(1 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_BOOKSHELF_WOOD_1, SPRITE_BOOKSHELF_WOOD_1_W, SPRITE_BOOKSHELF_WOOD_1_H);
    drawRGB565Sprite(6 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_BOOKSHELF_WOOD_1, SPRITE_BOOKSHELF_WOOD_1_W, SPRITE_BOOKSHELF_WOOD_1_H);
    drawRGB565Sprite(4 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_BOOKSHELF_WOOD_2, SPRITE_BOOKSHELF_WOOD_2_W, SPRITE_BOOKSHELF_WOOD_2_H);
    drawRGB565Sprite(0 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_PLANT_TOP_C, SPRITE_PLANT_TOP_C_W, SPRITE_PLANT_TOP_C_H);
    drawRGB565Sprite(9 * TILE_SIZE, 0 * TILE_SIZE, SPRITE_PLANT_TOP_D, SPRITE_PLANT_TOP_D_W, SPRITE_PLANT_TOP_D_H);
    drawRGB565Sprite(0 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_PLANT_BOTTOM_BROWN, SPRITE_PLANT_BOTTOM_BROWN_W, SPRITE_PLANT_BOTTOM_BROWN_H);
    drawRGB565Sprite(9 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_PLANT_BOTTOM_BROWN, SPRITE_PLANT_BOTTOM_BROWN_W, SPRITE_PLANT_BOTTOM_BROWN_H);
    drawRGB565Sprite(2 * TILE_SIZE, 6 * TILE_SIZE, SPRITE_LAPTOP_B, SPRITE_LAPTOP_B_W, SPRITE_LAPTOP_B_H);
    drawRGB565Sprite(7 * TILE_SIZE, 6 * TILE_SIZE, SPRITE_COMPUTER_B, SPRITE_COMPUTER_B_W, SPRITE_COMPUTER_B_H);
    drawRGB565Sprite(11 * TILE_SIZE, 6 * TILE_SIZE, SPRITE_PLANT_TOP_H, SPRITE_PLANT_TOP_H_W, SPRITE_PLANT_TOP_H_H);
    drawRGB565Sprite(11 * TILE_SIZE, 7 * TILE_SIZE, SPRITE_PLANT_BOTTOM_WHITE, SPRITE_PLANT_BOTTOM_WHITE_W, SPRITE_PLANT_BOTTOM_WHITE_H);
    drawRGB565Sprite(14 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_MICROWAVE, SPRITE_MICROWAVE_W, SPRITE_MICROWAVE_H);
    drawRGB565Sprite(11 * TILE_SIZE, 1 * TILE_SIZE, SPRITE_TRASH, SPRITE_TRASH_W, SPRITE_TRASH_H);
    drawRGB565Sprite(1 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_COMPUTER_E, SPRITE_COMPUTER_E_W, SPRITE_COMPUTER_E_H);
    drawRGB565Sprite(7 * TILE_SIZE, 12 * TILE_SIZE, SPRITE_COMPUTER_G, SPRITE_COMPUTER_G_W, SPRITE_COMPUTER_G_H);
    drawRGB565Sprite(6 * TILE_SIZE, 4 * TILE_SIZE, SPRITE_LAPTOP_C, SPRITE_LAPTOP_C_W, SPRITE_LAPTOP_C_H);
    drawRGB565Sprite(3 * TILE_SIZE, 4 * TILE_SIZE, SPRITE_LAPTOP_D, SPRITE_LAPTOP_D_W, SPRITE_LAPTOP_D_H);
    drawRGB565Sprite(8 * TILE_SIZE, 3 * TILE_SIZE, SPRITE_BOX, SPRITE_BOX_W, SPRITE_BOX_H);
    drawRGB565Sprite(6 * TILE_SIZE, 2 * TILE_SIZE, SPRITE_BOXES_2, SPRITE_BOXES_2_W, SPRITE_BOXES_2_H);
    drawRGB565Sprite(1 * TILE_SIZE, 2 * TILE_SIZE, SPRITE_BOXES_1, SPRITE_BOXES_1_W, SPRITE_BOXES_1_H);
}

void Renderer::drawCharacter(const Character& ch) {
    int sittingOff = (ch.state == CharState::TYPE || ch.state == CharState::READ) ? SITTING_OFFSET_PX : 0;
    int drawY = (int)(ch.y + sittingOff) - CHAR_H;
    if (drawY + CHAR_H <= _clipYMin || drawY >= _clipYMax) return;

    // WHY: ACTIVITY frame selection is split here and in getFrameIndex() because
    // non-READING activities need a standing pose (frame 1) that bypasses the
    // state→frame mapping, while READING reuses the READ animation via getFrameIndex().
    int localFrame;
    if (ch.state == CharState::ACTIVITY && ch.idleActivity != IdleActivity::READING) {
        localFrame = 1;  // standing pose for coffee/water/socializing
    } else {
        localFrame = getFrameIndex(ch.state, ch.frame);
    }
    if (localFrame < 0) return;

    Dir renderDir = ch.dir;
    bool flipH = false;
    if (ch.dir == Dir::LEFT) {
        renderDir = Dir::RIGHT;
        flipH = true;
    }

    int frameIdx = static_cast<int>(renderDir) * FRAMES_PER_DIR + localFrame;
    if (frameIdx >= CHAR_TEMPLATE_COUNT) return;

    int charIdx = ch.palette % NUM_PALETTES;
    const uint16_t* sprite = CHAR_SPRITES[charIdx][frameIdx];

    int drawX = (int)(ch.x) - CHAR_W / 2;

    drawRGB565SpriteFlip(drawX, drawY, sprite, CHAR_W, CHAR_H, flipH);
}

void Renderer::drawDog(const Pet& pet, DogColor color) {
    int dogDrawY = (int)(pet.y) - DOG_H;
    if (dogDrawY + DOG_H <= _clipYMin || dogDrawY >= _clipYMax) return;

    int frameIdx;
    bool flipH = (pet.dir == Dir::LEFT);

    if (pet.behavior == DogBehavior::NAP) {
        frameIdx = DOG_LAYDOWN_IDX;
    } else if (pet.isSitting) {
        frameIdx = DOG_SIT_IDX;
    } else if (pet.isPeeing) {
        frameIdx = DOG_PEE_IDX;
    } else if (pet.walking) {
        if (pet.isRunning) {
            frameIdx = DOG_RUN_BASE + (pet.frame % DOG_RUN_COUNT);
        } else {
            frameIdx = DOG_WALK_BASE + (pet.frame % DOG_WALK_COUNT);
        }
    } else {
        // Idle: cycle through 8 frames
        frameIdx = DOG_IDLE_BASE + (pet.idleFrame % DOG_IDLE_COUNT);
    }

    if (frameIdx < 0 || frameIdx >= DOG_FRAME_COUNT) frameIdx = DOG_IDLE_BASE;

    uint8_t colorIdx = static_cast<uint8_t>(color);
    if (colorIdx >= DOG_COLOR_COUNT) colorIdx = static_cast<uint8_t>(DOG_DEFAULT_COLOR);
    const uint16_t* const* spriteTable =
        (const uint16_t* const*)pgm_read_ptr(&DOG_COLOR_SPRITES[colorIdx]);
    if (!spriteTable) return;
    const uint16_t* sprite = (const uint16_t*)pgm_read_ptr(&spriteTable[frameIdx]);
    if (!sprite) return;
    int drawX = (int)(pet.x) - DOG_W / 2;
    int drawY = (int)(pet.y) - DOG_H;
    drawRGB565SpriteFlip(drawX, drawY, sprite, DOG_W, DOG_H, flipH);
}

void Renderer::drawSpawnEffect(const Character& ch) {
    int spawnDrawY = (int)(ch.y) - CHAR_H;
    if (spawnDrawY + CHAR_H <= _clipYMin || spawnDrawY >= _clipYMax) return;

    float progress = ch.effectTimer / SPAWN_DURATION_SEC;
    if (progress > 1.0f) progress = 1.0f;
    if (ch.state == CharState::DESPAWN) {
        progress = 1.0f - progress;
    }

    Dir renderDir = ch.dir;
    bool flipH = false;
    if (ch.dir == Dir::LEFT) {
        renderDir = Dir::RIGHT;
        flipH = true;
    }

    int frameIdx = static_cast<int>(renderDir) * FRAMES_PER_DIR + 1; // standing frame
    if (frameIdx >= CHAR_TEMPLATE_COUNT) return;

    int charIdx = ch.palette % NUM_PALETTES;
    const uint16_t* sprite = CHAR_SPRITES[charIdx][frameIdx];

    int drawX = (int)(ch.x) - CHAR_W / 2;
    int drawY = (int)(ch.y) - CHAR_H;

    int revealCols = (int)(progress * CHAR_W);

    for (int col = 0; col < revealCols && col < CHAR_W; col++) {
        int srcCol = flipH ? (CHAR_W - 1 - col) : col;
        for (int row = 0; row < CHAR_H; row++) {
            uint16_t color = sprite[row * CHAR_W + srcCol];
            if (color == 0x0000) continue; // transparent

            // Green tint for matrix effect
            if (progress < 0.8f) {
                float greenBlend = 1.0f - (progress / 0.8f);
                uint8_t r = ((color >> 11) & 0x1F) << 3;
                uint8_t g = ((color >> 5) & 0x3F) << 2;
                uint8_t b = (color & 0x1F) << 3;
                r = (uint8_t)(r * (1.0f - greenBlend));
                g = (uint8_t)(g + (255 - g) * greenBlend * 0.5f);
                b = (uint8_t)(b * (1.0f - greenBlend));
                color = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
            }

            int dx = drawX + col;
            int dy = drawY + row;
            if (dx >= 0 && dx < SCREEN_W && dy >= 0 && dy < SCREEN_H) {
                gfxDrawPixel(dx, dy, color);
            }
        }
    }
}

void Renderer::drawBubble(const Character& ch) {
    // Bubble is above the character's head — estimate worst-case Y for clip check
    int sittingOff2 = (ch.state == CharState::TYPE || ch.state == CharState::READ) ? SITTING_OFFSET_PX : 0;
    int bubbleTopEst = (int)(ch.y + sittingOff2) - CHAR_H - 20;  // ~max bubble height
    int bubbleBotEst = (int)(ch.y + sittingOff2) - CHAR_H;
    if (bubbleBotEst <= _clipYMin || bubbleTopEst >= _clipYMax) return;

    const uint16_t* bubbleData;
    int bw, bh;

    if (ch.bubbleType == 1) {
        bubbleData = SPRITE_BUBBLE_PERMISSION;
        bw = SPRITE_BUBBLE_PERMISSION_W;
        bh = SPRITE_BUBBLE_PERMISSION_H;
    } else if (ch.bubbleType == 2) {
        bubbleData = SPRITE_BUBBLE_WAITING;
        bw = SPRITE_BUBBLE_WAITING_W;
        bh = SPRITE_BUBBLE_WAITING_H;
    } else if (ch.bubbleType == 3) {
        // Info bubble: draw text-based bubble with agent ID and state
        int sittingOffset = (ch.state == CharState::TYPE || ch.state == CharState::READ) ? SITTING_OFFSET_PX : 0;

        char label[16];
        snprintf(label, sizeof(label), "Agent %d", ch.id + 1);

        int textW = 6 * (int)strlen(label); // font2 approx 6px per char at size 1
        int padX = 3;
        int padY = 2;
        int bw2 = textW + padX * 2;
        int bh2 = 10 + padY * 2;

        int bubbleX = (int)(ch.x) - bw2 / 2;
        int bubbleY = (int)(ch.y + sittingOffset) - CHAR_H - bh2 - 2;

        // Clamp to screen
        if (bubbleX < 0) bubbleX = 0;
        if (bubbleX + bw2 > SCREEN_W) bubbleX = SCREEN_W - bw2;
        if (bubbleY < 0) bubbleY = 0;

        // Background
        gfxFillRect(bubbleX, bubbleY, bw2, bh2, 0xFFFF);
        // Border
        gfxFillRect(bubbleX, bubbleY, bw2, 1, 0x0000);
        gfxFillRect(bubbleX, bubbleY + bh2 - 1, bw2, 1, 0x0000);
        gfxFillRect(bubbleX, bubbleY, 1, bh2, 0x0000);
        gfxFillRect(bubbleX + bw2 - 1, bubbleY, 1, bh2, 0x0000);

        // Text
        gfxSetTextColor(0x0000);
        gfxSetTextSize(1);
        gfxDrawString(label, bubbleX + padX, bubbleY + padY);
        return;
    } else {
        return;
    }

    int sittingOffset = (ch.state == CharState::TYPE || ch.state == CharState::READ) ? SITTING_OFFSET_PX : 0;
    int bubbleX = (int)(ch.x) - bw / 2;
    int bubbleY = (int)(ch.y + sittingOffset) - CHAR_H - bh - 2;

    drawRGB565Sprite(bubbleX, bubbleY, bubbleData, bw, bh);
}

void Renderer::drawStatusBar(OfficeState& office) {
    int y = SCREEN_H - STATUS_BAR_H;
    if (y + STATUS_BAR_H <= _clipYMin || y >= _clipYMax) return;
    gfxFillRect(0, y, SCREEN_W, STATUS_BAR_H, COLOR_STATUS);

    // ── Left side: transport icons ──
    int iconY = y + (STATUS_BAR_H - TRANSPORT_ICON_H) / 2;
    int textLeft = 1;  // tracks where status text can start

    // USB icon (all boards)
    uint16_t usbColor = office.isSerialConnected() ? COLOR_ACTIVE : COLOR_DIM;
    gfxDrawMonoBitmap(1, iconY, ICON_USB, TRANSPORT_ICON_W, TRANSPORT_ICON_H, usbColor);
    textLeft = 1 + TRANSPORT_ICON_W + 1;

#if defined(HAS_BLE)
    // BLE icon (CYD/CYD-S3 only)
    uint16_t btColor = office.isBleConnected() ? COLOR_BLE : COLOR_DIM;
    gfxDrawMonoBitmap(textLeft, iconY, ICON_BT, TRANSPORT_ICON_W, TRANSPORT_ICON_H, btColor);
    textLeft += TRANSPORT_ICON_W + 2;
#endif

    // ── Right side: battery + hamburger ──
    int rightBound = SCREEN_W;
#if defined(HAS_TOUCH)
    // Reserve space for hamburger icon
    int hx = SCREEN_W - HAMBURGER_W - HAMBURGER_MARGIN;
    int hy = y + (STATUS_BAR_H - HAMBURGER_H) / 2;
    drawHamburgerIcon(hx, hy);
    rightBound = hx - 2;
#endif

#if defined(HAS_BATTERY)
    // Battery percentage + charging bolt
    uint8_t battPct = battery_getPercent();
    bool charging = battery_isCharging();

    char battBuf[8];
    snprintf(battBuf, sizeof(battBuf), "%d%%", battPct);
    int battTextW = 6 * (int)strlen(battBuf);

    uint16_t battColor;
    if (battPct > BATTERY_WARN_PCT) battColor = COLOR_ACTIVE;          // green
    else if (battPct > BATTERY_CRIT_PCT) battColor = COLOR_CHARGING;  // yellow
    else battColor = COLOR_DISCONNECTED;                               // red

    int battX;
    if (charging) {
        // bolt icon + space + percentage text
        battX = rightBound - battTextW - TRANSPORT_ICON_W - 2;
        gfxDrawMonoBitmap(battX, iconY, ICON_BOLT, TRANSPORT_ICON_W, TRANSPORT_ICON_H, COLOR_CHARGING);
        gfxSetTextColor(battColor);
        gfxSetTextSize(1);
        gfxDrawString(battBuf, battX + TRANSPORT_ICON_W + 1, y + 1);
    } else {
        battX = rightBound - battTextW - 1;
        gfxSetTextColor(battColor);
        gfxSetTextSize(1);
        gfxDrawString(battBuf, battX, y + 1);
    }
    rightBound = battX - 2;
#endif

    // ── Center: status content ──
    gfxSetTextColor(COLOR_TEXT);
    gfxSetTextSize(1);

    char buf[64];

    switch (office.getStatusMode()) {
        case StatusMode::OVERVIEW: {
            int activeCount = office.getActiveAgentCount();
            snprintf(buf, sizeof(buf), "%d/%d active", activeCount, MAX_AGENTS);
            gfxDrawString(buf, textLeft, y + 1);
            if (!office.isConnected()) {
                uint16_t pin = office.getBlePin();
                if (pin > 0) {
                    snprintf(buf, sizeof(buf), "BLE:%u", pin);
                    int pinW = 6 * (int)strlen(buf);
                    int discW = 6 * 12; // "Disconnected" = 12 chars
                    int discX = rightBound - pinW - 4 - discW;
                    gfxDrawString("Disconnected", discX, y + 1);
                    gfxDrawString(buf, rightBound - pinW, y + 1);
                } else {
                    int discW = 6 * 12;
                    gfxDrawString("Disconnected", rightBound - discW, y + 1);
                }
            }
            break;
        }
        case StatusMode::USAGE_STATS: {
            const UsageStats& us = office.getUsageStats();
            if (!us.valid) {
                gfxDrawString("No usage data", textLeft, y + 1);
                break;
            }
            int barW = 40;
            int barH = 6;
            int barY = y + 2;

            // Current usage
            gfxDrawString("C", textLeft, y + 1);
            int barX = textLeft + 8;
            gfxFillRect(barX, barY, barW, barH, COLOR_DIM);
            int fillW = (us.currentPct * barW) / 100;
            uint16_t barColor = us.currentPct >= 80 ? 0xF800 : us.currentPct >= 50 ? 0xFDA0 : 0x07E0;
            if (fillW > 0) gfxFillRect(barX, barY, fillW, barH, barColor);

            char pctBuf[8];
            snprintf(pctBuf, sizeof(pctBuf), "%d%%", us.currentPct);
            gfxDrawString(pctBuf, barX + barW + 2, y + 1);

            char rstBuf[12];
            uint16_t m = us.currentResetMin;
            if (m >= 1440) snprintf(rstBuf, sizeof(rstBuf), "%dd%dh", m / 1440, (m % 1440) / 60);
            else if (m >= 60) snprintf(rstBuf, sizeof(rstBuf), "%dh%dm", m / 60, m % 60);
            else snprintf(rstBuf, sizeof(rstBuf), "%dm", m);

            int pctW = (int)strlen(pctBuf) * 6;
            gfxSetTextColor(0x7BEF);
            gfxDrawString(rstBuf, barX + barW + 2 + pctW + 3, y + 1);
            gfxSetTextColor(COLOR_TEXT);

            // Weekly usage
            int wStart = 160;
            gfxDrawString("W", wStart, y + 1);
            int wBarX = wStart + 8;
            gfxFillRect(wBarX, barY, barW, barH, COLOR_DIM);
            int wFillW = (us.weeklyPct * barW) / 100;
            uint16_t wBarColor = us.weeklyPct >= 80 ? 0xF800 : us.weeklyPct >= 50 ? 0xFDA0 : 0x07E0;
            if (wFillW > 0) gfxFillRect(wBarX, barY, wFillW, barH, wBarColor);

            snprintf(pctBuf, sizeof(pctBuf), "%d%%", us.weeklyPct);
            gfxDrawString(pctBuf, wBarX + barW + 2, y + 1);

            m = us.weeklyResetMin;
            if (m >= 1440) snprintf(rstBuf, sizeof(rstBuf), "%dd%dh", m / 1440, (m % 1440) / 60);
            else if (m >= 60) snprintf(rstBuf, sizeof(rstBuf), "%dh%dm", m / 60, m % 60);
            else snprintf(rstBuf, sizeof(rstBuf), "%dm", m);

            pctW = (int)strlen(pctBuf) * 6;
            gfxSetTextColor(0x7BEF);
            gfxDrawString(rstBuf, wBarX + barW + 2 + pctW + 3, y + 1);
            gfxSetTextColor(COLOR_TEXT);
            break;
        }
        case StatusMode::AGENT_LIST: {
            int pos = textLeft;
            const Character* chars = office.getCharacters();
            for (int i = 0; i < MAX_AGENTS; i++) {
                if (!chars[i].alive) continue;
                const char* stateStr;
                switch (chars[i].state) {
                    case CharState::TYPE:    stateStr = "TYP"; break;
                    case CharState::READ:    stateStr = "RD";  break;
                    case CharState::IDLE:    stateStr = "IDL"; break;
                    case CharState::WALK:     stateStr = "WLK"; break;
                    case CharState::ACTIVITY: stateStr = "ACT"; break;
                    case CharState::SPAWN:   stateStr = "SPN"; break;
                    case CharState::DESPAWN: stateStr = "DSP"; break;
                    default:                 stateStr = "?";   break;
                }
                snprintf(buf, sizeof(buf), "%d:%s", chars[i].id + 1, stateStr);
                gfxDrawString(buf, pos, y + 1);
                pos += 6 * (int)strlen(buf) + 4;
                if (pos > rightBound - 20) break;
            }
            break;
        }
        case StatusMode::PERFORMANCE: {
            snprintf(buf, sizeof(buf), "%.1f FPS", (double)_fps);
            gfxDrawString(buf, textLeft, y + 1);
            break;
        }
        case StatusMode::UPTIME: {
            uint32_t sec = millis() / 1000;
            uint32_t h = sec / 3600;
            uint32_t m = (sec % 3600) / 60;
            uint32_t s = sec % 60;
            snprintf(buf, sizeof(buf), "%lu:%02lu:%02lu", (unsigned long)h, (unsigned long)m, (unsigned long)s);
            gfxDrawString(buf, textLeft, y + 1);
            break;
        }
    }
}

int Renderer::getFrameIndex(CharState state, uint8_t frame) const {
    switch (state) {
        case CharState::WALK:
            switch (frame % 4) {
                case 0: return 0;
                case 1: return 1;
                case 2: return 2;
                case 3: return 1;
            }
            break;
        case CharState::TYPE:
            return 3 + (frame % 2);
        case CharState::READ:
            return 5 + (frame % 2);
        case CharState::ACTIVITY:
            return 5 + (frame % 2);  // READ frames (used for READING activity)
        case CharState::IDLE:
            return 1;
        default:
            return 1;
    }
    return 1;
}

#if defined(HAS_TOUCH)
void Renderer::drawHamburgerIcon(int x, int y) {
    // Three 7x1 white bars with 1px gaps
    gfxFillRect(x, y,     HAMBURGER_W, 1, COLOR_TEXT);
    gfxFillRect(x, y + 2, HAMBURGER_W, 1, COLOR_TEXT);
    gfxFillRect(x, y + 4, HAMBURGER_W, 1, COLOR_TEXT);
}

void Renderer::drawMenuOverlay(OfficeState& office) {
    DogSettings ds = office.getDogSettings();

    // Menu position: right-aligned, above status bar
    int menuX = SCREEN_W - MENU_W - 4;
    int menuY = SCREEN_H - STATUS_BAR_H - MENU_H - 2;

    // Background
    gfxFillRect(menuX, menuY, MENU_W, MENU_H, COLOR_MENU_BG);
    // Border
    gfxFillRect(menuX, menuY, MENU_W, 1, COLOR_MENU_BORDER);
    gfxFillRect(menuX, menuY + MENU_H - 1, MENU_W, 1, COLOR_MENU_BORDER);
    gfxFillRect(menuX, menuY, 1, MENU_H, COLOR_MENU_BORDER);
    gfxFillRect(menuX + MENU_W - 1, menuY, 1, MENU_H, COLOR_MENU_BORDER);

    gfxSetTextSize(1);

    int textPad = (MENU_ITEM_H - 10) / 2;  // vertically center 10px font in row

    // Row 0: Title
    gfxSetTextColor(COLOR_TEXT);
    gfxDrawString("Settings", menuX + 6, menuY + textPad);

    // Separator line
    gfxFillRect(menuX + 2, menuY + MENU_ITEM_H - 2, MENU_W - 4, 1, COLOR_MENU_BORDER);

    // Row 1: Dog toggle
    int row1Y = menuY + MENU_ITEM_H;
    gfxSetTextColor(COLOR_TEXT);
    gfxDrawString("Dog:", menuX + 6, row1Y + textPad);
    gfxSetTextColor(ds.enabled ? COLOR_ACTIVE : COLOR_DISCONNECTED);
    gfxDrawString(ds.enabled ? "ON" : "OFF", menuX + 36, row1Y + textPad);

    // Separator
    gfxFillRect(menuX + 2, menuY + MENU_ITEM_H * 2 - 2, MENU_W - 4, 1, COLOR_MENU_BORDER);

    // Row 2: Color swatches
    int row2Y = menuY + MENU_ITEM_H * 2;
    gfxSetTextColor(COLOR_TEXT);
    gfxDrawString("Color:", menuX + 6, row2Y + textPad);

    // Representative colors for each dog variant (RGB565)
    static const uint16_t SWATCH_COLORS[DOG_COLOR_COUNT] = {
        0x2104,  // black (dark gray)
        0x8262,  // brown
        0x8410,  // gray
        0xCC0A,  // tan
    };

    int swatchX = menuX + SWATCH_AREA_X;
    int swatchY = row2Y + 3;
    int swatchH = MENU_ITEM_H - 6;

    for (int i = 0; i < DOG_COLOR_COUNT; i++) {
        int sx = swatchX + i * (SWATCH_W + SWATCH_GAP);

        if (!ds.enabled) {
            // Dimmed when dog disabled
            gfxFillRect(sx, swatchY, SWATCH_W, swatchH, 0x1082);
        } else {
            gfxFillRect(sx, swatchY, SWATCH_W, swatchH, SWATCH_COLORS[i]);
            // Green highlight border on selected color
            if (static_cast<uint8_t>(ds.color) == i) {
                gfxFillRect(sx - 1, swatchY - 1, SWATCH_W + 2, 1, COLOR_ACTIVE);
                gfxFillRect(sx - 1, swatchY + swatchH, SWATCH_W + 2, 1, COLOR_ACTIVE);
                gfxFillRect(sx - 1, swatchY - 1, 1, swatchH + 2, COLOR_ACTIVE);
                gfxFillRect(sx + SWATCH_W, swatchY - 1, 1, swatchH + 2, COLOR_ACTIVE);
            }
        }
    }

    // Separator
    gfxFillRect(menuX + 2, menuY + MENU_ITEM_H * 3 - 2, MENU_W - 4, 1, COLOR_MENU_BORDER);

    // Row 3: Flip screen toggle
    bool flipped = office.isScreenFlipped();
    int row3Y = menuY + MENU_ITEM_H * 3;
    gfxSetTextColor(COLOR_TEXT);
    gfxDrawString("Flip:", menuX + 6, row3Y + textPad);
    gfxSetTextColor(flipped ? COLOR_ACTIVE : COLOR_DISCONNECTED);
    gfxDrawString(flipped ? "ON" : "OFF", menuX + 40, row3Y + textPad);

#if defined(HAS_SOUND)
    // Separator
    gfxFillRect(menuX + 2, menuY + MENU_ITEM_H * 4 - 2, MENU_W - 4, 1, COLOR_MENU_BORDER);

    // Row 4: Sound toggle
    bool soundOn = office.isSoundEnabled();
    int row4Y = menuY + MENU_ITEM_H * 4;
    gfxSetTextColor(COLOR_TEXT);
    gfxDrawString("Sound:", menuX + 6, row4Y + textPad);
    gfxSetTextColor(soundOn ? COLOR_ACTIVE : COLOR_DISCONNECTED);
    gfxDrawString(soundOn ? "ON" : "OFF", menuX + 48, row4Y + textPad);

    // Separator
    gfxFillRect(menuX + 2, menuY + MENU_ITEM_H * 5 - 2, MENU_W - 4, 1, COLOR_MENU_BORDER);

    // Row 5: Sleep
    int sleepRowY = menuY + MENU_ITEM_H * 5;
    gfxSetTextColor(COLOR_INACTIVE);
    gfxDrawString("Sleep...", menuX + 6, sleepRowY + textPad);
#else
    // Separator (no sound row, sleep is row 4)
    gfxFillRect(menuX + 2, menuY + MENU_ITEM_H * 4 - 2, MENU_W - 4, 1, COLOR_MENU_BORDER);

    // Row 4: Sleep
    int sleepRowY = menuY + MENU_ITEM_H * 4;
    gfxSetTextColor(COLOR_INACTIVE);
    gfxDrawString("Sleep...", menuX + 6, sleepRowY + textPad);
#endif

}
#endif

void Renderer::drawRGB565SpriteFlip(int x, int y, const uint16_t* data, int w, int h, bool flipH) {
    if (y + h <= _clipYMin || y >= _clipYMax) return;
    for (int row = 0; row < h; row++) {
        for (int col = 0; col < w; col++) {
            int srcCol = flipH ? (w - 1 - col) : col;
            uint16_t px = data[row * w + srcCol];
            if (px == 0x0000) continue; // transparent
            int dx = x + col;
            int dy = y + row;
            if (dx >= 0 && dx < SCREEN_W && dy >= 0 && dy < SCREEN_H) {
                gfxDrawPixel(dx, dy, px);
            }
        }
    }
}

// ── Screenshot capture ──────────────────────────────────────

void Renderer::requestScreenshot() {
    _screenshotRequested = true;
}

bool Renderer::isScreenshotPending() {
    if (_screenshotRequested) {
        _screenshotRequested = false;
        return true;
    }
    return false;
}

void Renderer::sendScreenshotHeader(uint16_t w, uint16_t h) {
    uint8_t hdr[12];
    uint32_t totalPixels = (uint32_t)w * h;
    hdr[0] = SCREENSHOT_SYNC1;
    hdr[1] = SCREENSHOT_SYNC2;
    hdr[2] = (w >> 8) & 0xFF;
    hdr[3] = w & 0xFF;
    hdr[4] = (h >> 8) & 0xFF;
    hdr[5] = h & 0xFF;
    hdr[6] = (totalPixels >> 24) & 0xFF;
    hdr[7] = (totalPixels >> 16) & 0xFF;
    hdr[8] = (totalPixels >> 8) & 0xFF;
    hdr[9] = totalPixels & 0xFF;
    hdr[10] = 0;
    hdr[11] = 0;
    Serial.write(hdr, 12);
}

void Renderer::rleEncodeBuffer(const uint16_t* buf, uint32_t pixelCount,
                               uint8_t* rleBuf, int& bufPos,
                               uint16_t& runPixel, uint16_t& runCount,
                               bool swapped) {
    for (uint32_t i = 0; i < pixelCount; i++) {
        uint16_t px = buf[i];
        if (swapped) px = (px << 8) | (px >> 8);

        if (runCount == 0) {
            runPixel = px;
            runCount = 1;
        } else if (px == runPixel && runCount < 0xFFFF) {
            runCount++;
        } else {
            rleBuf[bufPos++] = (runCount >> 8) & 0xFF;
            rleBuf[bufPos++] = runCount & 0xFF;
            rleBuf[bufPos++] = (runPixel >> 8) & 0xFF;
            rleBuf[bufPos++] = runPixel & 0xFF;
            if (bufPos >= 252) {
                Serial.write(rleBuf, bufPos);
                bufPos = 0;
            }
            runPixel = px;
            runCount = 1;
        }
    }
}

void Renderer::rleFlushEnd(uint8_t* rleBuf, int& bufPos,
                           uint16_t runPixel, uint16_t runCount) {
    if (bufPos > 248) {
        Serial.write(rleBuf, bufPos);
        bufPos = 0;
    }
    // Last run
    rleBuf[bufPos++] = (runCount >> 8) & 0xFF;
    rleBuf[bufPos++] = runCount & 0xFF;
    rleBuf[bufPos++] = (runPixel >> 8) & 0xFF;
    rleBuf[bufPos++] = runPixel & 0xFF;
    // End marker
    rleBuf[bufPos++] = 0;
    rleBuf[bufPos++] = 0;
    rleBuf[bufPos++] = 0;
    rleBuf[bufPos++] = 0;
    Serial.write(rleBuf, bufPos);
}

void Renderer::sendScreenshot() {
    if (_frameBuffer) {
        // LILYGO: full framebuffer in PSRAM
        sendScreenshotHeader(SCREEN_W, SCREEN_H);
        uint32_t totalPixels = (uint32_t)SCREEN_W * SCREEN_H;
        uint8_t rleBuf[256];
        int bufPos = 0;
        uint16_t runPixel = 0, runCount = 0;
        bool swapped = _canvas->getSwapBytes();
        rleEncodeBuffer(_frameBuffer, totalPixels, rleBuf, bufPos,
                        runPixel, runCount, swapped);
        rleFlushEnd(rleBuf, bufPos, runPixel, runCount);
        return;
    }

    if (_directMode || !_canvas) {
        // Direct mode: no buffer at all — send empty response
        uint8_t hdr[12];
        hdr[0] = SCREENSHOT_SYNC1;
        hdr[1] = SCREENSHOT_SYNC2;
        memset(&hdr[2], 0, 10);
        Serial.write(hdr, 12);
        uint8_t end[4] = {0, 0, 0, 0};
        Serial.write(end, 4);
        return;
    }

    // Strip-mode: re-render each strip and capture
    sendScreenshotFromDisplay();
}

void Renderer::sendSplashScreenshot(Splash& splash) {
    // Direct mode: no buffer — send empty response
    if (_directMode || !_canvas) {
        uint8_t hdr[12];
        hdr[0] = SCREENSHOT_SYNC1;
        hdr[1] = SCREENSHOT_SYNC2;
        memset(&hdr[2], 0, 10);
        Serial.write(hdr, 12);
        uint8_t end[4] = {0, 0, 0, 0};
        Serial.write(end, 4);
        return;
    }

    // Re-draw splash content into sprite buffer for capture
    sendScreenshotHeader(SCREEN_W, SCREEN_H);

    uint8_t rleBuf[256];
    int bufPos = 0;
    uint16_t runPixel = 0, runCount = 0;
    bool swapped = _canvas->getSwapBytes();

    if (_frameBuffer) {
        // LILYGO: full-size buffer — single pass
        _canvas->fillSprite(TFT_BLACK);
        splash.drawTo(_canvas, 0);
        rleEncodeBuffer(_frameBuffer, (uint32_t)SCREEN_W * SCREEN_H,
                        rleBuf, bufPos, runPixel, runCount, swapped);
    } else {
        // CYD: strip buffer — N passes
        uint16_t* stripBuf = (uint16_t*)_canvas->getPointer();
        if (!stripBuf) return;

        for (int s = 0; s < _stripCount; s++) {
            int stripTop = s * _stripHeight;
            int stripBot = stripTop + _stripHeight;
            if (stripBot > SCREEN_H) stripBot = SCREEN_H;
            int thisStripH = stripBot - stripTop;
            uint32_t stripPixels = (uint32_t)SCREEN_W * thisStripH;

            _canvas->fillSprite(TFT_BLACK);
            splash.drawTo(_canvas, -stripTop);
            rleEncodeBuffer(stripBuf, stripPixels, rleBuf, bufPos,
                            runPixel, runCount, swapped);
        }
    }

    rleFlushEnd(rleBuf, bufPos, runPixel, runCount);
}

void Renderer::sendScreenshotFromDisplay() {
    // CYD strip-mode: re-render each strip into the sprite buffer and capture
    if (!_currentOffice) {
        // No office state yet — send empty screenshot response
        uint8_t hdr[12];
        hdr[0] = SCREENSHOT_SYNC1; hdr[1] = SCREENSHOT_SYNC2;
        memset(&hdr[2], 0, 10);
        Serial.write(hdr, 12);
        uint8_t end[4] = {0, 0, 0, 0};
        Serial.write(end, 4);
        return;
    }

    uint16_t* stripBuf = (uint16_t*)_canvas->getPointer();
    if (!stripBuf) return;

    sendScreenshotHeader(SCREEN_W, SCREEN_H);

    // Save clip state — renderFrame() sets these per-strip, but callers may
    // read them between sendScreenshotFromDisplay() and the next renderFrame().
    int savedClipMin = _clipYMin, savedClipMax = _clipYMax, savedYOff = _yOffset;

    uint8_t rleBuf[256];
    int bufPos = 0;
    uint16_t runPixel = 0, runCount = 0;
    bool swapped = _canvas->getSwapBytes();

    for (int s = 0; s < _stripCount; s++) {
        int stripTop = s * _stripHeight;
        int stripBot = stripTop + _stripHeight;
        if (stripBot > SCREEN_H) stripBot = SCREEN_H;
        int thisStripH = stripBot - stripTop;
        uint32_t stripPixels = (uint32_t)SCREEN_W * thisStripH;

        _clipYMin = stripTop;
        _clipYMax = stripBot;
        _yOffset = -stripTop;

        _canvas->fillSprite(COLOR_BG);
        drawScene(*_currentOffice);
        rleEncodeBuffer(stripBuf, stripPixels, rleBuf, bufPos,
                        runPixel, runCount, swapped);
    }

    _clipYMin = savedClipMin; _clipYMax = savedClipMax; _yOffset = savedYOff;
    rleFlushEnd(rleBuf, bufPos, runPixel, runCount);
}

void Renderer::drawRGB565Sprite(int x, int y, const uint16_t* data, int w, int h) {
    if (y + h <= _clipYMin || y >= _clipYMax) return;
    for (int row = 0; row < h; row++) {
        for (int col = 0; col < w; col++) {
            uint16_t px = data[row * w + col];
            if (px == 0x0000) continue; // transparent
            int dx = x + col;
            int dy = y + row;
            if (dx >= 0 && dx < SCREEN_W && dy >= 0 && dy < SCREEN_H) {
                gfxDrawPixel(dx, dy, px);
            }
        }
    }
}
