#ifndef SPRITES_DOG_H
#define SPRITES_DOG_H

// Master dog sprite header — includes all color variants
// Generated by tools/convert_dog.py

#include "dog_black.h"
#include "dog_brown.h"
#include "dog_gray.h"
#include "dog_tan.h"

#define DOG_FRAME_PIXELS (475)
#define DOG_FRAME_COUNT 23
// DOG_COLOR_COUNT defined in config.h (constexpr)

static const uint16_t* const* const DOG_COLOR_SPRITES[4] PROGMEM = {
    DOG_BLACK_SPRITES,
    DOG_BROWN_SPRITES,
    DOG_GRAY_SPRITES,
    DOG_TAN_SPRITES,
};

// Backward-compatible alias (tan)
#define DOG_SPRITES DOG_TAN_SPRITES

#endif // SPRITES_DOG_H