#!/usr/bin/env python3
"""
convert_dog.py - Generate multi-color dog sprite headers from PNG sprite sheets.

Reads assets/Dog Animation/doggy-{color}.png (125x95, 5x5 grid of 25x19 frames):
  Frame 0:     Sit (1)
  Frames 1-8:  Idle (8)
  Frames 9-16: Run (8)
  Frame 17:    Pee (1)
  Frame 18:    Lay down (1)
  Frames 19-22: Walk (4)
  Frames 23-24: Empty

Output:
  firmware/src/sprites/dog_black.h
  firmware/src/sprites/dog_brown.h
  firmware/src/sprites/dog_gray.h
  firmware/src/sprites/dog_tan.h
  firmware/src/sprites/dog.h (master include)
"""

import sys
from pathlib import Path
from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
ASSETS_DIR = PROJECT_DIR / "assets" / "Dog Animation"
OUTPUT_DIR = PROJECT_DIR / "firmware" / "src" / "sprites"

COLORS = ["black", "brown", "gray", "tan"]

FRAME_W = 25
FRAME_H = 19
GRID_COLS = 5
GRID_ROWS = 5
TOTAL_FRAMES = 23  # last 2 cells are empty


def rgba_to_rgb565(r, g, b, a):
    """Convert RGBA pixel to RGB565. Returns 0x0000 for transparent pixels."""
    if a < 128:
        return 0x0000
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def extract_frame(img, idx):
    """Extract a single frame from the sprite sheet by linear index."""
    col = idx % GRID_COLS
    row = idx // GRID_COLS
    x0 = col * FRAME_W
    y0 = row * FRAME_H
    frame = img.crop((x0, y0, x0 + FRAME_W, y0 + FRAME_H))
    pixels = []
    for y in range(FRAME_H):
        for x in range(FRAME_W):
            r, g, b, a = frame.getpixel((x, y))
            pixels.append(rgba_to_rgb565(r, g, b, a))
    return pixels


def format_array(name, pixels):
    lines = [f"static const uint16_t {name}[{len(pixels)}] PROGMEM = {{"]
    for i in range(0, len(pixels), FRAME_W):
        row = pixels[i:i + FRAME_W]
        vals = ", ".join(f"0x{v:04X}" for v in row)
        comma = "," if i + FRAME_W < len(pixels) else ""
        lines.append(f"    {vals}{comma}")
    lines.append("};")
    return "\n".join(lines)


FRAME_SUFFIXES = [
    "SIT",
    "IDLE1", "IDLE2", "IDLE3", "IDLE4",
    "IDLE5", "IDLE6", "IDLE7", "IDLE8",
    "RUN1", "RUN2", "RUN3", "RUN4",
    "RUN5", "RUN6", "RUN7", "RUN8",
    "PEE",
    "LAYDOWN",
    "WALK1", "WALK2", "WALK3", "WALK4",
]


def generate_color_header(color, img):
    """Generate a per-color header file."""
    prefix = f"DOG_{color.upper()}"
    guard = f"SPRITES_DOG_{color.upper()}_H"

    frame_data = []
    for idx in range(TOTAL_FRAMES):
        name = f"{prefix}_{FRAME_SUFFIXES[idx]}"
        pixels = extract_frame(img, idx)
        frame_data.append((name, pixels))

    parts = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        f"// 25x19 Dog Sprites — {color} variant",
        "// Generated by tools/convert_dog.py",
    ]

    for name, pixels in frame_data:
        parts.append("")
        parts.append(format_array(name, pixels))

    # Sprite table for this color
    parts.append("")
    parts.append(f"static const uint16_t* const {prefix}_SPRITES[{TOTAL_FRAMES}] PROGMEM = {{")
    for name, _ in frame_data:
        parts.append(f"    {name},")
    parts.append("};")

    parts.append("")
    parts.append(f"#endif // {guard}")

    return "\n".join(parts)


def generate_master_header():
    """Generate the master dog.h that includes all color headers."""
    parts = [
        "#ifndef SPRITES_DOG_H",
        "#define SPRITES_DOG_H",
        "",
        "// Master dog sprite header — includes all color variants",
        "// Generated by tools/convert_dog.py",
        "",
    ]

    for color in COLORS:
        parts.append(f'#include "dog_{color}.h"')

    parts.append("")
    parts.append(f"#define DOG_FRAME_PIXELS ({FRAME_W * FRAME_H})")
    parts.append(f"#define DOG_FRAME_COUNT {TOTAL_FRAMES}")
    parts.append(f"// DOG_COLOR_COUNT defined in config.h (constexpr)")
    parts.append("")

    # Array of pointers to per-color sprite tables
    parts.append(f"static const uint16_t* const* const DOG_COLOR_SPRITES[{len(COLORS)}] PROGMEM = {{")
    for color in COLORS:
        prefix = f"DOG_{color.upper()}"
        parts.append(f"    {prefix}_SPRITES,")
    parts.append("};")

    # Backward-compatible alias: DOG_SPRITES points to tan (default)
    parts.append("")
    parts.append("// Backward-compatible alias (tan)")
    parts.append("#define DOG_SPRITES DOG_TAN_SPRITES")

    parts.append("")
    parts.append("#endif // SPRITES_DOG_H")

    return "\n".join(parts)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for color in COLORS:
        input_path = ASSETS_DIR / f"doggy-{color}.png"
        if not input_path.exists():
            print(f"Error: {input_path} not found")
            sys.exit(1)

        img = Image.open(input_path).convert("RGBA")
        expected = (GRID_COLS * FRAME_W, GRID_ROWS * FRAME_H)
        assert img.size == expected, \
            f"{input_path.name}: expected {expected[0]}x{expected[1]}, got {img.size}"

        header = generate_color_header(color, img)
        output_path = OUTPUT_DIR / f"dog_{color}.h"
        output_path.write_text(header)
        print(f"Generated {output_path} ({TOTAL_FRAMES} frames, {FRAME_W}x{FRAME_H})")

    # Master header
    master = generate_master_header()
    master_path = OUTPUT_DIR / "dog.h"
    master_path.write_text(master)
    print(f"Generated {master_path} (master, {len(COLORS)} colors)")


if __name__ == "__main__":
    main()
