#!/usr/bin/env python3
"""
convert_sound.py - Convert MP3 files to C PCM headers for ESP32 playback.

Converts MP3 -> 24kHz mono 16-bit signed LE PCM -> C header with PROGMEM array.
Requires ffmpeg on PATH.

Usage:
    python3 tools/convert_sound.py assets/sounds/dog-bark.mp3
    python3 tools/convert_sound.py assets/sounds/*.mp3           # batch mode
    python3 tools/convert_sound.py -n startup_sound file.mp3     # custom name

Output goes to firmware/src/sounds/<name>_pcm.h with:
    static const uint8_t <NAME>_PCM[] PROGMEM = { ... };
    static const uint32_t <NAME>_PCM_LEN = <byte_count>;
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
OUTPUT_DIR = PROJECT_DIR / "firmware" / "src" / "sounds"

SAMPLE_RATE = 24000
BYTES_PER_LINE = 12  # hex values per line


def slugify(name: str) -> str:
    """Convert filename stem to C-safe identifier.

    'dragon-studio-dog-bark-494308' -> 'dog_bark'
    Strips known prefixes (dragon-studio-, freesound_community-) and
    trailing numeric IDs.
    """
    # Strip known source prefixes
    name = re.sub(r"^dragon[_-]studio[_-]", "", name)
    name = re.sub(r"^freesound[_-]community[_-]", "", name)
    # Strip trailing numeric ID (e.g., -494308)
    name = re.sub(r"[_-]\d{4,}$", "", name)
    # Replace non-alnum with underscore, collapse, strip
    name = re.sub(r"[^a-zA-Z0-9]+", "_", name)
    name = name.strip("_")
    return name


def convert_mp3_to_pcm(mp3_path: Path) -> bytes:
    """Convert MP3 to raw 24kHz mono s16le PCM via ffmpeg."""
    with tempfile.NamedTemporaryFile(suffix=".raw", delete=True) as tmp:
        cmd = [
            "ffmpeg", "-y", "-i", str(mp3_path),
            "-ar", str(SAMPLE_RATE),
            "-ac", "1",
            "-f", "s16le",
            "-acodec", "pcm_s16le",
            tmp.name
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"ffmpeg error for {mp3_path.name}:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            sys.exit(1)
        return Path(tmp.name).read_bytes()


def generate_header(array_name: str, pcm_data: bytes) -> str:
    """Generate C header string from PCM byte data."""
    lines = [
        "#pragma once",
        "#include <stdint.h>",
        "#include <pgmspace.h>",
        "",
        "// Generated by tools/convert_sound.py",
        f"// {SAMPLE_RATE}Hz mono 16-bit signed LE PCM",
        "",
        f"static const uint8_t {array_name}[] PROGMEM = {{",
    ]

    for i in range(0, len(pcm_data), BYTES_PER_LINE):
        chunk = pcm_data[i:i + BYTES_PER_LINE]
        vals = ", ".join(f"0x{b:02X}" for b in chunk)
        comma = "," if i + BYTES_PER_LINE < len(pcm_data) else ""
        lines.append(f"  {vals}{comma}")

    lines.append("};")
    lines.append(f"static const uint32_t {array_name}_LEN = {len(pcm_data)};")
    lines.append("")

    return "\n".join(lines)


def convert_file(mp3_path: Path, name_override: Optional[str] = None) -> None:
    """Convert a single MP3 file to a C header."""
    slug = name_override if name_override else slugify(mp3_path.stem)
    if not slug:
        print(f"Error: could not derive a valid name from {mp3_path.name}. "
              f"Use -n to specify one.", file=sys.stderr)
        sys.exit(1)
    array_name = slug.upper() + "_PCM"
    output_name = slug.lower() + "_pcm.h"
    output_path = OUTPUT_DIR / output_name

    pcm_data = convert_mp3_to_pcm(mp3_path)
    if len(pcm_data) == 0:
        print(f"Error: ffmpeg produced zero bytes for {mp3_path.name}", file=sys.stderr)
        sys.exit(1)
    header = generate_header(array_name, pcm_data)
    output_path.write_text(header)

    duration_sec = len(pcm_data) / (SAMPLE_RATE * 2)
    print(f"Generated {output_path.relative_to(PROJECT_DIR)} "
          f"({len(pcm_data)} bytes, {duration_sec:.1f}s, {SAMPLE_RATE}Hz)")


def main():
    # Simple arg parsing: -n NAME applies to the single following file
    args = sys.argv[1:]
    if not args:
        print(f"Usage: {sys.argv[0]} [-n name] <mp3_file> [mp3_file ...]")
        print(f"  -n name  Override output name (only valid with single file)")
        print(f"Output: firmware/src/sounds/<name>_pcm.h")
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Check ffmpeg
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
    except FileNotFoundError:
        print("Error: ffmpeg not found on PATH", file=sys.stderr)
        sys.exit(1)

    name_override = None
    files = []
    i = 0
    while i < len(args):
        if args[i] == "-n":
            if i + 1 >= len(args):
                print("Error: -n requires a name argument", file=sys.stderr)
                sys.exit(1)
            name_override = args[i + 1]
            i += 2
        else:
            files.append(Path(args[i]).resolve())
            i += 1

    if name_override and len(files) != 1:
        print("Error: -n can only be used with a single input file", file=sys.stderr)
        sys.exit(1)

    for mp3_path in files:
        if not mp3_path.exists():
            print(f"Error: {mp3_path} not found", file=sys.stderr)
            sys.exit(1)
        convert_file(mp3_path, name_override)


if __name__ == "__main__":
    main()
