#!/usr/bin/env python3
"""
convert_dog.py - Generate dog sprite header from PNG sprite sheet.

Reads assets/doggy3.png (125x95, 5x5 grid of 25x19 frames):
  Frame 0:     Sit (1)
  Frames 1-8:  Idle (8)
  Frames 9-16: Run (8)
  Frame 17:    Pee (1)
  Frame 18:    Lay down (1)
  Frames 19-22: Walk (4)
  Frames 23-24: Empty

Output: firmware/src/sprites/dog.h
"""

from pathlib import Path
from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
INPUT_PATH = PROJECT_DIR / "assets" / "doggy3.png"
OUTPUT_PATH = PROJECT_DIR / "firmware" / "src" / "sprites" / "dog.h"

FRAME_W = 25
FRAME_H = 19
GRID_COLS = 5
GRID_ROWS = 5
TOTAL_FRAMES = 23  # last 2 cells are empty

FRAME_NAMES = [
    "DOG_SIT",
    "DOG_IDLE1", "DOG_IDLE2", "DOG_IDLE3", "DOG_IDLE4",
    "DOG_IDLE5", "DOG_IDLE6", "DOG_IDLE7", "DOG_IDLE8",
    "DOG_RUN1", "DOG_RUN2", "DOG_RUN3", "DOG_RUN4",
    "DOG_RUN5", "DOG_RUN6", "DOG_RUN7", "DOG_RUN8",
    "DOG_PEE",
    "DOG_LAYDOWN",
    "DOG_WALK1", "DOG_WALK2", "DOG_WALK3", "DOG_WALK4",
]


def rgba_to_rgb565(r, g, b, a):
    """Convert RGBA pixel to RGB565. Returns 0x0000 for transparent pixels."""
    if a < 128:
        return 0x0000
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def extract_frame(img, idx):
    """Extract a single frame from the sprite sheet by linear index."""
    col = idx % GRID_COLS
    row = idx // GRID_COLS
    x0 = col * FRAME_W
    y0 = row * FRAME_H
    frame = img.crop((x0, y0, x0 + FRAME_W, y0 + FRAME_H))
    pixels = []
    for y in range(FRAME_H):
        for x in range(FRAME_W):
            r, g, b, a = frame.getpixel((x, y))
            pixels.append(rgba_to_rgb565(r, g, b, a))
    return pixels


def format_array(name, pixels):
    lines = [f"static const uint16_t {name}[{len(pixels)}] PROGMEM = {{"]
    for i in range(0, len(pixels), FRAME_W):
        row = pixels[i:i + FRAME_W]
        vals = ", ".join(f"0x{v:04X}" for v in row)
        comma = "," if i + FRAME_W < len(pixels) else ""
        lines.append(f"    {vals}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main():
    if not INPUT_PATH.exists():
        print(f"Error: {INPUT_PATH} not found")
        return

    img = Image.open(INPUT_PATH).convert("RGBA")
    assert img.size == (GRID_COLS * FRAME_W, GRID_ROWS * FRAME_H), \
        f"Expected {GRID_COLS * FRAME_W}x{GRID_ROWS * FRAME_H}, got {img.size}"

    frame_data = []
    for idx in range(TOTAL_FRAMES):
        name = FRAME_NAMES[idx]
        pixels = extract_frame(img, idx)
        frame_data.append((name, pixels))

    parts = [
        "#ifndef SPRITES_DOG_H",
        "#define SPRITES_DOG_H",
        "",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        f"// {FRAME_W}x{FRAME_H} Dog Sprites (extracted from doggy3.png)",
        "// Generated by tools/convert_dog.py",
        "",
        f"#define DOG_FRAME_PIXELS ({FRAME_W * FRAME_H})",
        f"#define DOG_FRAME_COUNT {TOTAL_FRAMES}",
        "",
    ]

    for name, pixels in frame_data:
        parts.append("")
        parts.append(format_array(name, pixels))

    parts.append("")
    parts.append(f"static const uint16_t* const DOG_SPRITES[{TOTAL_FRAMES}] PROGMEM = {{")
    for name, _ in frame_data:
        parts.append(f"    {name},")
    parts.append("};")

    parts.append("")
    parts.append("#endif")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(parts))

    print(f"Generated {OUTPUT_PATH} ({TOTAL_FRAMES} frames, {FRAME_W}x{FRAME_H})")


if __name__ == "__main__":
    main()
