#!/usr/bin/env python3
"""
convert_characters.py - Convert character sprite sheet PNGs to ESP32 RGB565 header.

Reads char_0.png through char_5.png from assets/characters/ and generates
firmware/src/sprites/characters.h with direct RGB565 sprite data per character.

Sprite sheet layout (112x96 PNG, 16x32 frames):
  - 3 rows: Down (0), Up (1), Right (2). Left = flip Right at runtime.
  - 7 columns: walk1, walk2(standing), walk3, type1, type2, read1, read2

Requires Pillow: pip install Pillow

Usage:
    python3 tools/convert_characters.py
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
ASSETS_DIR = PROJECT_ROOT / "assets" / "characters"
OUTPUT_PATH = PROJECT_ROOT / "firmware" / "src" / "sprites" / "characters.h"

NUM_CHARACTERS = 6
FRAME_W = 16
FRAME_H = 32
COLS = 7  # frames per direction
ROWS = 3  # directions: down, up, right
FRAMES_PER_CHAR = ROWS * COLS  # 21


def rgb_to_565(r: int, g: int, b: int) -> int:
    """Convert 8-bit RGB to RGB565."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def extract_frames(img: Image.Image) -> list[list[int]]:
    """Extract all 21 frames from a 112x96 RGBA sprite sheet.

    Returns list of 21 frames, each a list of FRAME_W*FRAME_H RGB565 values.
    Transparent pixels are 0x0000.
    """
    if img.mode != "RGBA":
        img = img.convert("RGBA")

    frames = []
    for row in range(ROWS):
        for col in range(COLS):
            x0 = col * FRAME_W
            y0 = row * FRAME_H
            pixels = []
            for y in range(FRAME_H):
                for x in range(FRAME_W):
                    r, g, b, a = img.getpixel((x0 + x, y0 + y))
                    if a < 128:
                        pixels.append(0x0000)
                    else:
                        pixels.append(rgb_to_565(r, g, b))
            frames.append(pixels)
    return frames


def format_array(name: str, pixels: list[int], w: int, h: int) -> str:
    """Format a single sprite frame as a C array."""
    lines = [f"static const uint16_t {name}[{w * h}] PROGMEM = {{"]
    for row in range(h):
        vals = []
        for col in range(w):
            vals.append(f"0x{pixels[row * w + col]:04X}")
        comma = "," if row < h - 1 else ""
        lines.append(f"    {', '.join(vals)}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main():
    # Verify assets exist
    missing = []
    for i in range(NUM_CHARACTERS):
        path = ASSETS_DIR / f"char_{i}.png"
        if not path.exists():
            missing.append(str(path))
    if missing:
        print("Error: Missing character sprite sheets:")
        for m in missing:
            print(f"  {m}")
        print("\nDownload from: https://github.com/pablodelucca/pixel-agents")
        sys.exit(1)

    print(f"Converting {NUM_CHARACTERS} character sprite sheets...")

    # Frame name mapping: direction_index * 7 + frame_index
    dir_names = ["DOWN", "UP", "RIGHT"]
    frame_names = ["WALK1", "WALK2", "WALK3", "TYPE1", "TYPE2", "READ1", "READ2"]

    all_chars = []
    for ci in range(NUM_CHARACTERS):
        path = ASSETS_DIR / f"char_{ci}.png"
        img = Image.open(path)
        if img.size != (112, 96):
            print(f"Warning: {path.name} is {img.size}, expected (112, 96)")
        frames = extract_frames(img)
        all_chars.append(frames)
        print(f"  char_{ci}.png: {len(frames)} frames extracted")

    # Generate header
    out = []
    out.append("#ifndef SPRITES_CHARACTERS_H")
    out.append("#define SPRITES_CHARACTERS_H")
    out.append("")
    out.append("#include <Arduino.h>")
    out.append("#include <pgmspace.h>")
    out.append("")
    out.append("// =============================================================================")
    out.append("// Character Sprites - Direct RGB565")
    out.append("// Generated by tools/convert_characters.py -- DO NOT EDIT BY HAND")
    out.append("// =============================================================================")
    out.append("//")
    out.append("// Source: pixel-agents VS Code extension by @pablodelucca")
    out.append("// Character art based on JIK-A-4 Metro City sprite pack")
    out.append("//")
    out.append("// Each character has 21 frames (3 directions x 7 animations).")
    out.append("// Frames are 16x32 pixels stored as RGB565. 0x0000 = transparent.")
    out.append("// LEFT-facing sprites are rendered by flipping RIGHT at runtime.")
    out.append("//")
    out.append("// Directions: DOWN=0, UP=1, RIGHT=2")
    out.append("// Frames per dir: walk1, walk2(standing), walk3, type1, type2, read1, read2")
    out.append("")
    out.append('#include "../config.h"')
    out.append("")
    out.append(f"#define CHAR_FRAME_PIXELS ({FRAME_W} * {FRAME_H})  // {FRAME_W * FRAME_H}")
    out.append(f"#define NUM_CHAR_SPRITES {NUM_CHARACTERS}")
    out.append(f"#define CHAR_FRAMES_TOTAL {FRAMES_PER_CHAR}")
    out.append("")

    # Template indices (keep compatible with existing enum)
    out.append("// Template indices (compatible with existing renderer)")
    out.append("enum CharTemplate {")
    idx = 0
    for di, dn in enumerate(dir_names):
        for fi, fn in enumerate(frame_names):
            out.append(f"    TPL_{dn}_{fn} = {idx},")
            idx += 1
    out.append(f"    CHAR_TEMPLATE_COUNT = {idx}")
    out.append("};")
    out.append("")

    # Emit sprite arrays
    for ci in range(NUM_CHARACTERS):
        out.append(f"// ── Character {ci} ─────────────────────────────────────")
        for fi, frame_pixels in enumerate(all_chars[ci]):
            di = fi // COLS
            frame_idx = fi % COLS
            name = f"CHAR{ci}_{dir_names[di]}_{frame_names[frame_idx]}"
            out.append(format_array(name, frame_pixels, FRAME_W, FRAME_H))
            out.append("")

    # Emit lookup table: CHAR_SPRITES[char_index][frame_index] -> pixel data
    out.append("// ── Sprite lookup table ───────────────────────────────")
    out.append(f"static const uint16_t* const CHAR_SPRITES[{NUM_CHARACTERS}][{FRAMES_PER_CHAR}] PROGMEM = {{")
    for ci in range(NUM_CHARACTERS):
        entries = []
        for fi in range(FRAMES_PER_CHAR):
            di = fi // COLS
            frame_idx = fi % COLS
            entries.append(f"CHAR{ci}_{dir_names[di]}_{frame_names[frame_idx]}")
        out.append(f"    {{ // Character {ci}")
        # Print 7 per line (one direction per line)
        for di in range(ROWS):
            start = di * COLS
            end = start + COLS
            line_entries = entries[start:end]
            comma = "," if di < ROWS - 1 or ci < NUM_CHARACTERS - 1 else ""
            out.append(f"        {', '.join(line_entries)}{comma}")
        out.append(f"    }},")
    out.append("};")
    out.append("")
    out.append("#endif // SPRITES_CHARACTERS_H")
    out.append("")

    # Write output
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(out)
    OUTPUT_PATH.write_text(content)

    size_kb = len(content) / 1024
    pixel_data_bytes = NUM_CHARACTERS * FRAMES_PER_CHAR * FRAME_W * FRAME_H * 2
    print(f"\nGenerated: {OUTPUT_PATH}")
    print(f"  Header size: {size_kb:.1f} KB")
    print(f"  Sprite data: {pixel_data_bytes / 1024:.1f} KB in PROGMEM")
    print(f"  {NUM_CHARACTERS} characters x {FRAMES_PER_CHAR} frames x {FRAME_W}x{FRAME_H} = {pixel_data_bytes:,} bytes")


if __name__ == "__main__":
    main()
