#!/usr/bin/env python3
"""
convert_robot.py - Convert robot walk sprite sheet to ESP32 RGB565 header.

Reads 'robot walk.png' from assets/characters/ and generates
firmware/src/sprites/robot.h with 6 walk-cycle frames.

Sprite sheet layout (128x192 PNG, 64x64 frames):
  - 2 columns x 3 rows = 6 frames (walk cycle)
  - Content area: 24x30 pixels (bbox x19,y18 to x43,y48)
  - Scaled to ROBOT_W x ROBOT_H via nearest-neighbor

Requires Pillow: pip install Pillow

Usage:
    python3 tools/convert_robot.py
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install with: pip install Pillow")
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
INPUT_PATH = PROJECT_ROOT / "assets" / "characters" / "robot walk.png"
OUTPUT_PATH = PROJECT_ROOT / "firmware" / "src" / "sprites" / "robot.h"

# Source layout
SHEET_COLS = 2
SHEET_ROWS = 3
FRAME_SIZE = 64  # each frame canvas is 64x64

# Content bounding box within each 64x64 frame
CROP_X = 19
CROP_Y = 18
CROP_W = 24  # x19 to x43
CROP_H = 30  # y18 to y48

# Output dimensions (50% of full-size agent height: 32 * 0.5 = 16)
ROBOT_W = 13
ROBOT_H = 16
FRAME_COUNT = SHEET_COLS * SHEET_ROWS  # 6


def rgb_to_565(r: int, g: int, b: int) -> int:
    """Convert 8-bit RGB to RGB565."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def extract_and_scale_frames(img: Image.Image) -> list[list[int]]:
    """Extract 6 frames, crop to content, scale to ROBOT_W x ROBOT_H.

    Returns list of 6 frames, each a list of ROBOT_W*ROBOT_H RGB565 values.
    """
    if img.mode != "RGBA":
        img = img.convert("RGBA")

    frames = []
    for row in range(SHEET_ROWS):
        for col in range(SHEET_COLS):
            # Crop to content area within the 64x64 frame
            x0 = col * FRAME_SIZE + CROP_X
            y0 = row * FRAME_SIZE + CROP_Y

            # Extract cropped content at source resolution (CROP_W x CROP_H)
            src_pixels = []
            for y in range(CROP_H):
                for x in range(CROP_W):
                    r, g, b, a = img.getpixel((x0 + x, y0 + y))
                    if a < 128:
                        src_pixels.append(0x0000)
                    else:
                        src_pixels.append(rgb_to_565(r, g, b))

            # Nearest-neighbor scale to output size
            scaled = []
            for oy in range(ROBOT_H):
                sy = oy * CROP_H // ROBOT_H
                for ox in range(ROBOT_W):
                    sx = ox * CROP_W // ROBOT_W
                    scaled.append(src_pixels[sy * CROP_W + sx])

            frames.append(scaled)
    return frames


def format_array(name: str, pixels: list[int], w: int, h: int) -> str:
    """Format a single sprite frame as a C array."""
    lines = [f"static const uint16_t {name}[{w * h}] PROGMEM = {{"]
    for row in range(h):
        vals = []
        for col in range(w):
            vals.append(f"0x{pixels[row * w + col]:04X}")
        comma = "," if row < h - 1 else ""
        lines.append(f"    {', '.join(vals)}{comma}")
    lines.append("};")
    return "\n".join(lines)


def main():
    if not INPUT_PATH.exists():
        print(f"Error: Robot sprite not found: {INPUT_PATH}")
        sys.exit(1)

    img = Image.open(INPUT_PATH)
    if img.size != (128, 192):
        print(f"Warning: {INPUT_PATH.name} is {img.size}, expected (128, 192)")

    print(f"Converting robot sprite sheet...")
    frames = extract_and_scale_frames(img)
    print(f"  {len(frames)} frames extracted and scaled to {ROBOT_W}x{ROBOT_H}")

    # Generate header
    out = []
    out.append("#ifndef SPRITES_ROBOT_H")
    out.append("#define SPRITES_ROBOT_H")
    out.append("")
    out.append("#include <Arduino.h>")
    out.append("#include <pgmspace.h>")
    out.append("")
    out.append("// =============================================================================")
    out.append("// Robot Mini-Agent Sprites - RGB565")
    out.append("// Generated by tools/convert_robot.py -- DO NOT EDIT BY HAND")
    out.append("// =============================================================================")
    out.append("//")
    out.append(f"// {FRAME_COUNT} walk-cycle frames, {ROBOT_W}x{ROBOT_H} pixels each.")
    out.append("// Front-facing only (no directional variants). 0x0000 = transparent.")
    out.append("")
    out.append(f"#define ROBOT_W {ROBOT_W}")
    out.append(f"#define ROBOT_H {ROBOT_H}")
    out.append(f"#define ROBOT_FRAME_COUNT {FRAME_COUNT}")
    out.append(f"#define ROBOT_FRAME_PIXELS ({ROBOT_W} * {ROBOT_H})  // {ROBOT_W * ROBOT_H}")
    out.append("")

    frame_names = []
    for i, pixels in enumerate(frames):
        name = f"ROBOT_FRAME_{i}"
        frame_names.append(name)
        out.append(format_array(name, pixels, ROBOT_W, ROBOT_H))
        out.append("")

    # Lookup table
    out.append("// ── Robot sprite lookup table ─────────────────────────")
    out.append(f"static const uint16_t* const ROBOT_SPRITES[{FRAME_COUNT}] PROGMEM = {{")
    out.append(f"    {', '.join(frame_names)}")
    out.append("};")
    out.append("")
    out.append("#endif // SPRITES_ROBOT_H")
    out.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(out)
    OUTPUT_PATH.write_text(content)

    data_bytes = FRAME_COUNT * ROBOT_W * ROBOT_H * 2
    print(f"\nGenerated: {OUTPUT_PATH}")
    print(f"  Header size: {len(content) / 1024:.1f} KB")
    print(f"  Sprite data: {data_bytes} bytes ({data_bytes / 1024:.1f} KB) in PROGMEM")
    print(f"  {FRAME_COUNT} frames x {ROBOT_W}x{ROBOT_H}")


if __name__ == "__main__":
    main()
